### ISSUE TITLE
 PageDown while pwsh is processing command => System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PSReadLine#1016]
Pressing  PageDown while pwsh is processing command gives System.PlatformNotSupportedException
### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 7.0.0-preview.3
OS: Linux 4.4.0-18898-Microsoft #1000-Microsoft Fri May 10 16:34:00 PST 2019
Last 17 Keys
```
 l l Enter
 l s Enter
 c d Spacebar I m Tab Enter
 l s Enter
 PageDown
```

### Exception
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by msftrncs** [comment]
I can add that on Ubuntu 18.04, page-up or page-down result in a 'not supported on this platform' error.  This is an error message from the .Net Core console libraries indicating that they do not support the function of setting the window position, which PSReadLine is attempting to use to move the window a page up or down on your request.

**Comment by msftrncs** [comment]
This is probably just a duplicate to #700.

**Comment by AndrewSav** [comment]
Guys, could you please explain something to me? You closed this as fixed. How do I get the fix? After `Install-Module PSReadLine -AllowPrerelease -Force` and restarting powershell I'm getting then same exception. 

The upgrade section of the readme says "If you are using the version of PSReadLine that ships with Windows 10" - I did not,  and then "If you've installed PSReadLine yourself from the PowerShell Gallery" - I did not.  It was installed as described [here in the official powershell documentation](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1804).

No upgrade instructions for that case.

And then is says "With the preview release of PowerShellGet for PowerShell V3/V4, downloads from GitHub are deprecated".

So it looks like for all intents and purposes while you seem to have fixed the issue this fix is not really avaible to general public.

Can you keep the issue open until the release (so that I and others could get notification, when it's aviailble) or provide clear instructions for upgrade?

Thank you in advance!

**Comment by daxian-dbw** [comment]
The issue is fixed by #1032.
If you want to get the fix immediately, please open the AppVeyor CI page from that PR, and download the `PSReadLine.zip` from the `Artifacts` tab. Then replace the files in your current `PSReadLine` module folder with the files from that zip file.

As for the `upgrade section`, I will update it to make it clear what to do for people using the one shipped by pwsh.

**Comment by AndrewSav** [comment]
@daxian-dbw very much appreciated!

**Comment by daxian-dbw** [comment]
PR #1034 was submitted to update the `README`. Please let me know if it's still not clear in any aspects.
