### ISSUE TITLE
Expand PSReadLine MenuComplete to work in Visual Studio Code for non-english default languages

### ISSUE THREAD

**Issue by WorrenB** [PowerShell/PSReadLine#1086]
this is my second issue on github. 
I hope it is usable in this form.
```
PS version: 7.0.0-preview.4
PSReadline version: 2.0.0-beta5
os: 10.0.18362.356 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: Visual Studio Code Host
BufferWidth: 160
BufferHeight: 19
```
Behavior:
If windows default language is set to english the PSReadLine MenuComplete in Visual Studio Code - Insiders works out of the box as intended.
```
Completion functions
====================
Key           Function            Description
---           --------            -----------
Ctrl+@        MenuComplete        Complete the input if there is a single completion, otherwise complete the input by selecting from a menu of possible completions.
Ctrl+Spacebar MenuComplete        Complete the input if there is a single completion, otherwise complete the input by selecting from a menu of possible completions.
```

as my default language usually is set to german, I'm encountering problems while trying <kbd>Ctrl</kbd>+<kbd>Space</kbd> for calling MenuCompletion.
<kbd>Ctrl</kbd>+<kbd>Space</kbd> is then interpreted as <kbd>ctrl</kbd>+<kbd>"</kbd>
even switching keyboard layout then to english with <kbd>Shift</kbd>+<kbd>Alt</kbd> makes no difference.
Defining a additional PSReadLineKeyHandler s.b. fixed it for me, but due it works in english without any changes maybe there is a chance to "expand" it work for other languages too.
```
Set-PSReadLineKeyHandler -Chord 'Ctrl+"' -Function MenuComplete
```
```
Completion functions
====================
Key           Function            Description
---           --------            -----------
Ctrl+@        MenuComplete        Complete the input if there is a single completion, otherwise complete the input by selecting from a menu of possible completions.
Ctrl+Spacebar MenuComplete        Complete the input if there is a single completion, otherwise complete the input by selecting from a menu of possible completions.
Ctrl+"        MenuComplete        Complete the input if there is a single completion, otherwise complete the input by selecting from a menu of possible completions.
```

Thank you
kind regards
Björn

**Comment by msftrncs** [comment]
Could this be a VS Code thing?   Does it happen to in a normal ConHost'd PowerShell?

**Comment by WorrenB** [comment]
no it doesn't happen in ConHost'd Powershell - so maybe it is.
but this was also the case with english win default language until [@TylerLeonhardt](https://github.com/PowerShell/PSReadLine/issues/877) fixed it somehow.
so I thought it would be ok to place it here.
can you move it then - if needed?

**Comment by daxian-dbw** [comment]
@TylerLeonhardt Do you remember how it was fixed with English being the default language?

**Comment by TylerLeonhardt** [comment]
Yes! I fixed it in https://github.com/PowerShell/PSReadLine/pull/878 where I added `Ctrl+@`. I think as long as it doesn't conflict with anything, we can add `Ctrl+"`.

That said... @Tyriar, do you know why `Ctrl+Space` would be interpreted differently in a German layout vs an English one?

**Comment by Tyriar** [comment]
@TylerLeonhardt no idea. `keyCode` 32 (space) should send `NUL` (\u0000) to the shell:

https://github.com/xtermjs/xterm.js/blob/cad9477eef22c0e505337c1f634f9f35a8804edc/src/common/input/Keyboard.ts#L331

**Comment by daxian-dbw** [comment]
> I think as long as it doesn't conflict with anything, we can add Ctrl+".

I'm not sure if we want to go that way. It's possible `Ctrl+Space` gets mapped to a different chord for another different keyboard layout ...

**Comment by TylerLeonhardt** [comment]
> I'm not sure if we want to go that way. 

Yes ideally we find a generic way of going about doing this but it's unclear who's causing the different behavior at this time. I know that PSReadLine has had an issue here and there in the passed wrt other keyboard layouts.

**Comment by WorrenB** [comment]
for me it is mysterious because, it somehow seems to make a difference which language is active before starting vscode while language switching in an open vscode doesn't change the behavior?

**Comment by daxian-dbw** [comment]
Going through all keyboard layout issues.
@WorrenB I know it's been quite a while, but any chance you can try this with the latest PowerShell VS Code extension (2020.3.0) and see if it still happens? Also, can you please try the same in Windows Terminal? Look [here](https://github.com/microsoft/terminal#installing-and-running-windows-terminal) for how to install it. Thanks!

**Comment by Livven** [comment]
@daxian-dbw Not the person you mentioned but can confirm this is an issue with the latest versions of VS Code and Windows Terminal.

**Comment by daxian-dbw** [comment]
Thanks @Livven. We also got a new report (#1415) for the same issue with 2.0.0 GA PSReadLine in Windows Terminal.

From @l-c-g:
> This may be related to #1380 (but I am already using PSReadLine 2.0) or #1086 (Windows Terminal and VS Code may share some code in this area, I don't know). It might also be related to microsoft/terminal#2865. From a comment in that issue, I understand that this is due to terminals handling <kbd>Ctrl</kbd>+<kbd>Space</kbd> as alias for <kbd>Ctrl</kbd>+<kbd>@</kbd>. Coincidentally, on a German keyboard you enter " as <kbd>Shift</kbd>+<kbd>2</kbd>, which is where the US layout has the @ glyph. This comment lead me to try and switch my keyboard layout to US; if I do, <kbd>Ctrl</kbd>+<kbd>Space</kbd> correctly invokes MenuComplete.
>
> To me, it looks like a complex interaction between Windows Terminal, PSReadLine and the keyboard layout. I cannot say, however, whether the problem is in PSReadLine or Windows Terminal (in which case I would gladly open an issue with them).

**Comment by sigmarising** [comment]
> Going through all keyboard layout issues.
> @WorrenB I know it's been quite a while, but any chance you can try this with the latest PowerShell VS Code extension (2020.3.0) and see if it still happens? Also, can you please try the same in Windows Terminal? Look [here](https://github.com/microsoft/terminal#installing-and-running-windows-terminal) for how to install it. Thanks!

My  Computer Enviroment:
* PS version: 7.0.2
* PSReadline version: 2.1.0-beta2
* OS: Windows10 2004(19041.329)
* VSCode: 1.46.0 stable
* Windows Terminal: 1.0.1401.0 stable

I also experience the `Ctrl+Space` not working with Chinese input. But after I use the screencast in VScode, I found **this may caused by key-binding conflict with different language Inputs**.

![Test for diffrent inputs](https://user-images.githubusercontent.com/25470568/84727340-623dfd00-afc1-11ea-8cd7-94b62064e9e5.gif)

I use Microsoft Chinese Pinyin (which can change EN/CN input by hitting keybind) Input all the time. When I test the `Ctrl+Space` in English (EN-US), Microsoft Janpanese, and Microsoft Chinese Input, **I find that VSCode can not get the `Space` key when I using the Chinese Input.**

Then I goto the settings of Microsoft Chinese Pinyin Input and find that it use the keybinding `Ctrl+Space` to change between EN/CN.

![image](https://user-images.githubusercontent.com/25470568/84727626-02942180-afc2-11ea-8d7c-85039e162452.png)

Then I disabled this key-bind, and `Ctrl+Space` works well with English, Janpanese, Chinese inputs both in Vscode and windows ternimal.

**Comment by daxian-dbw** [comment]
A bunch of key bindings used in PSReadLine get fixed in the most recent preview release of Windows Terminal (v1.1.1671.0), including <kbd>ctrl+space</kbd> (which doesn't need the <kbd>ctrl+@</kbd> workaround binding for `MenuComplete` anymore).
See https://github.com/microsoft/terminal/issues/879 for the issue, and https://github.com/microsoft/terminal/issues/879#issuecomment-646179386 for the release information.
@l-c-g Can you please install the preview version of Windows Terminal and see if `Ctrl+Space` works fine in the German keyboard as well?

**Comment by daxian-dbw** [comment]
@Tyriar Given the issue microsoft/terminal#879 fixed in Windows Terminal preview release, can it also be fixed in VSCode terminal?

<kbd>Ctrl+Space</kbd> in Windows Terminal (1.1.1671.0)
![image](https://user-images.githubusercontent.com/127450/85169867-65372880-b221-11ea-8e58-623e5edd9beb.png)

<kbd>Ctrl+Space</kbd> in VSCode terminal (1.46.1)
![image](https://user-images.githubusercontent.com/127450/85170102-c0691b00-b221-11ea-8cac-aa0794f65849.png)

**Comment by Tyriar** [comment]
@daxian-dbw well if we just need to enable `PSEUDOCONSOLE_WIN32_INPUT_MODE` to get this then yes, it will be months before conpty ships in Windows 10 though.

**Comment by WorrenB** [comment]
Oh sorry - had a look on the progress of my issue at the beginning and then left without looking at it anylonger. 
I will now read all your comments which came in meanwhile and answer questions if still open.

**Comment by WorrenB** [comment]
for me it is also 

<kbd>Ctrl</kbd>+<kbd>Space</kbd> in Windows Terminal Version: 1.1.2021.0 shows
![wt](https://user-images.githubusercontent.com/33653410/89308078-2266ce00-d672-11ea-807e-4a892419d70d.PNG)

<kbd>Ctrl</kbd>+<kbd>Space</kbd> in VSCode Version 1.48.0 Insider shows
![VSCode Insider](https://user-images.githubusercontent.com/33653410/89308676-d2d4d200-d672-11ea-8761-0ed8af18744c.PNG)

so it seems to be interpreted correct in Windows Terminal while in VSCode it still shows something diffrent.

**Comment by sakaldevverm** [comment]
![Uploading Screenshot (57).png…]()
please soutout my problam

**Comment by daxian-dbw** [comment]
@WorrenB It's been over 2.5 years since [we last check on this issue](https://github.com/PowerShell/PSReadLine/issues/1086#issuecomment-646811427). Given that this is rooted in VSCode terminal, not something we can fix in PSReadLine, I will close this issue. Can you please check again if the issue has been resolved in VSCode terminal? If not, can you please open an issue in the VSCode repository instead? Thanks!
