### ISSUE TITLE
Tab completion fails with a specific sequence

### ISSUE THREAD

**Issue by MathiasMagnus** [PowerShell/PSReadLine#1116]
Tab completion doesn't work when completion would start with `TY`? Contain `TY`?. 😀

Environment data
----------------
```
PS version: 7.0.0-preview.4
PSReadline version: 2.0.0-beta5
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 180
BufferHeight: 28
```
Steps to reproduce or exception report
--------------------------------------
In any folder
```
New-Item -Type Directory MATTY
```
Type `MA` and press Tab, completes as expected. Delete the line, type `MAT` and try to Tab-complete to `MATTY` and see nothing happening.
```
New-Item -Type Directory ASDFTYWHATEVER
```
Tab-completion works anywhere in the sequence, except between the T and the Y.

**Comment by msftrncs** [comment]
I am not quite sure I follow, as I cannot seem to reproduce any problem here.

@MathiasMagnus, can you give a better example, with an explanation of what you expected the completion to be and why?   Most all the code involving completions is actually in PowerShell itself,   This means that you can try the same TAB completion directly with PSReadLine unloaded to see if the issue still exists, and if it does, the problem lies with PowerShell, not PSReadLine.

**Comment by MathiasMagnus** [comment]
I removed PSReadline and indeed, the problem still persist. I'll move it over to PowerShell then...

FWIW the problem is that some patterns don't tab complete, even when it's totally unambigous. Someone suggested apps that are capable of recording a window and also show keypresses and save to a GIF. That would be useful for demonstration purposes. Do you know of such an app?

**Comment by msftrncs** [comment]
Please link your new issue in PowerShell to this one, by posting the URL of this issue in your post over there, to help others follow along if they find this issue here.   Thanks,
