### ISSUE TITLE
something went wrong while deleting the beginning characters of a line

### ISSUE THREAD

**Issue by MrDRamos** [PowerShell/PSReadLine#1152]
Steps to reproduce
--------------------------------------
1) Running from a pwsh.exe console I initialized a variable $t: $t = Get-OlcAzureContextToken
2) Then output $t: $t
3) Then entered the following command: New-TimeSpan -End $T.ExpiresOn.DateTime (See output)
4) Next I up-arrowed to retrieve and edit that command, and tried removing the "New-TimeSpan -End " part, at which point PSReadLine threw an exception.

**Comment by msftrncs** [comment]
@MrDRamos, It would help if you could provide the environment data obtained by the script in the New Issue template, and posted the exception report you received.  You can edit your post to add this information.

This sounds like #910, it stems from the 'END' being reached with a nested token element behind it.   I don't think the fix for this has been released yet, pretty sure, as I was able to repeat it on a virgin beta 5 install.  It is fixed in #1049.

**Comment by daxian-dbw** [comment]
Close via #1049.
