### ISSUE TITLE
ViModeIndicator = Cursor does not work in Windows Terminal

### ISSUE THREAD

**Issue by wu4** [PowerShell/PSReadLine#1233]
Using `Set-PSReadLineOption -EditMode vi -viModeIndicator Cursor` on Windows Terminal does not display any differences based on the mode you are in. It's likely due to Windows Terminal accepting the [DECSCUSR](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_) escape sequence as opposed to whatever Windows Console supported.

**Comment by msftrncs** [comment]
At least for ConsoleHost, the `console` API is used, which I think provides full control over the cursor.  Otherwise a VT sequence is used.   See `ConsoleLib.cs`

**Comment by gwojan** [comment]
From the `Set-PSReadLineOption` help:

```powershell
$OnViModeChange = [scriptblock]{
    if ($args[0] -eq 'Command') {
        # Set the cursor to a blinking block.
        Write-Host -NoNewLine "`e[1 q"
    }
    else {
        # Set the cursor to a blinking line.
        Write-Host -NoNewLine "`e[5 q"
    }
}

Set-PsReadLineOption -EditMode Vi
Set-PSReadLineOption -ViModeIndicator Script -ViModeChangeHandler $OnViModeChange
```
That's how I do things in my Windows Terminal...

**Comment by msftrncs** [comment]
~@gwojan, I had to tweak the last line, `Set-PSReadLineOption -ViModeIndicator Script -ViModeChangeHandler $function:OnViModeChange`. ~
**[UPDATE]** the script from above comment was updated to fix the issue.

Even then, it doesn't seem to work quite right.  Should the cursor change to a block immediately after pressing <kbd>Esc</kbd>?  I have to enter a command before cursor changes, and likewise when coming out, it doesn't change back to a line until I type an accepted character.

**Comment by msftrncs** [comment]
I can also add, the OP's reported behavior also seems to be occur in VS Code's terminal on Windows.  @gwojan, work-around seems to somewhat work, both in Windows Terminal and VS Code., though it seems delayed relative to how the OP's settings work in the original ConsoleHost.

**Comment by daxian-dbw** [comment]
This can be fixed by always using the standard escape sequence to change the cursor shape, when the underlying console/terminal supports VT100.
A quick change looks like this: https://github.com/daxian-dbw/PSReadLine/commit/d29dad98426992c2d9f3b92cebedd7d85c4a0fac

@msftrncs Like you said, in Windows Terminal and VS Code, the cursor doesn't change until the cursor is moved. But the same escape sequence works fine on Linux and macOS.
Maybe this is a Windows Terminal bug. Opened issue https://github.com/microsoft/terminal/issues/4106

[Update] Yes, it's a Windows Terminal issue: `conpty isn't immediately flushing the updated cursor shape to the terminal pipe.`

**Comment by daxian-dbw** [comment]
The Windows Terminal issue microsoft/terminal#4106 was fixed.
