### ISSUE TITLE
VI Mode ArgumentOutOfRangeException in Insert after <char> Escape s <char>

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PSReadLine#1258]
### Environment
PSReadLine: 2.0.0-rc1
PowerShell: 6.2.3
OS: Microsoft Windows 10.0.19536
Last 74 Keys
```
 S e t - P S R e a d L i n e O p t i o n Spacebar - E d i t M o d e Spacebar v i Spacebar - v i M o d e I n d i c a t o r Spacebar C u r s o r Enter
 Escape Escape Escape Escape s s Escape Escape Escape s Escape s s Escape s s
```

### Exception
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Text.StringBuilder.Insert(Int32 index, Char* value, Int32 valueCount)
   at System.Text.StringBuilder.Insert(Int32 index, Char value)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Environment data
----------------
PS version: 6.2.3
PSReadline version: 2.0.0-rc1'; ProjectUri = 'https://github.com/PowerShell/PSReadLine
os: 10.0.19536.1000 (WinBuild.160101.0800)
PS file version: 6.2.3.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 28

Reproduces in regular ConsoleHost as well.

Steps to reproduce
--------------------------------------

Disclaimer: I have absolutely no familiarity with VI.  Seems to be an asset for finding issues. 😄 

1. Ran command `Set-PSReadLineOption -EditMode vi -viModeIndicator Cursor`.
2. Press <kbd>Esc</kbd> numerous times, not knowing what I am doing.
3. Press <kbd>s</kbd>, that finally got me out of command mode???
4. Press <kbd>s</kbd> again.
5.  Press <kbd>Esc</kbd>, then press <kbd>s</kbd>,
6.  Press <kbd>s</kbd> one last time. 

At this point the exception occurs.

**Comment by daxian-dbw** [comment]
This is caused by the update of `_current` in `ViInsertWithDelete`:
https://github.com/PowerShell/PSReadLine/blob/7e688f0cd5ebaf702dc72052d8c2ce165546c394/PSReadLine/ReadLine.vi.cs#L594-L598

When there is only 1 character in the line, <kbd>s</kbd> will delete that char and move `_current` to 1, even though `_buffer` length would be 0.
A simpler repro is
1. Ran command `Set-PSReadLineOption -EditMode vi -viModeIndicator Cursor`.
2. Press <kbd>a</kbd>
3. Press <kbd>Esc</kbd>
4. Press <kbd>s</kbd>
4. Press <kbd>a</kbd> (exception occurs at this point)

There seems to be more issues with the `ViInsertWithDelete` function on how `_current` is handled, for one, `_current` could be changed in the above pasted code, but the rendering happens in `DeleteChar` rendered the result using the old `_current`, and that makes the cursor position shown on console is out of sync with `_current`.

**Comment by daxian-dbw** [comment]
Submitted #1262 to fix the exception.
