### ISSUE TITLE
$env:+<TAB> doesn't work in emacs mode

### ISSUE THREAD

**Issue by vors** [PowerShell/PSReadLine#126]
Repro:
type "$env:"+TAB

Expected:
string "$env:" preserves on the line,
completion variants have been offered

Actual:
string reduced to "$"
No completion offered
short noize in headphones

**Comment by n8v** [comment]
:+1: 

I am so happy to have PSReadLine but this is broken—when I hit tab it deletes everything back to the `$`:

![psreadline tab rage](https://cloud.githubusercontent.com/assets/709386/5968956/747670f6-a7ca-11e4-94bc-5f854e00de0f.gif)

**Comment by lzybkr** [comment]
Yes, I know it's broken, but there is a good explanation why.  The common prefix for all of the completions is '$' because one of the completions requires curly braces: ${env:ProgramFiles(x86)}.

I wanted to avoid interpreting the completions, which in this case would mean adding braces to all of the other completions.  But the problem goes beyond variables.

Maybe I should just go straight to MenuComplete when the common unambiguous prefix is shorter word to complete.

**Comment by n8v** [comment]
FWIW the exact thing I was trying to do when it came to my attention was to get it to show me the right way to spell/escape/quote `${env:ProgramFiles(x86)}` without googling it. Without PSReadline, it does if I keep tabbing...

**Comment by lzybkr** [comment]
Until this is fixed, I suggest using Ctrl+Space.

If you forget and hit tab, remember that you can undo (Ctrl+_ in emacs mode, Ctrl+z in Windows mode), then hit Ctrl+Space.

**Comment by n8v** [comment]
Thanks a lot for your attention and quick workaround.

**Comment by lzybkr** [comment]
I think this was fixed in #515 - at any rate, it doesn't repro anymore.
