### ISSUE TITLE
 bug in Korean input on utf-8

### ISSUE THREAD

**Issue by ackphill** [PowerShell/PSReadLine#1326]
My powershell's default code page is 949(ANSI/OEM - Korean).
In this configuration, there's no problem with typing korean.

But when I change page code to 65001(UTF-8), what ever I type korean, powershell shows me strange character or empty character.
Furthermore, whenever I type '져' and press space, powershell shows error
'Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new', which brings me here.

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
This issue will be closed because you didn't follow the bug report template to provide **environment data** and **repro steps**.
You can update your issue description and re-open the issue afterwards. Also, please try out the latest version of PSReadLine from PowerShell Gallery, tons of issues have been fixed in recent versions.
