### ISSUE TITLE
PSReadline 2.0.0 does not work on PS 5.1 Windows 2012R2 servers

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSReadLine#1390]
PSReadline 2.0.0 does not work on PS 5.1 Windows 2012R2 servers. The module shows as imported but highlighting does not appear on PS 5.1. PS 7 works as expected.

## Environment

```none
PS version: 5.1.14409.1018
PSReadline version: 2.0.0
os: 6.3.9600.16384 (winblue_rtm.130821-1623)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000
```

## Exception report

N/A

## Steps to reproduce

Install PSReadline 2.0.0 on Windows 2012R2 and restart PowerShell. The module will show as imported but does not work.

## Expected behavior

PSReadline works as expected

## Actual behavior

PSReadline does not work

**Comment by rjmholt** [comment]
Would you be able to share the .NET version PowerShell is running on here?

**Comment by ThomasNieto** [comment]
.NET Framework 4.5.2

**Comment by rjmholt** [comment]
> .NET Framework 4.5.2

Ah, yeah, PSRL is currently built for .NET 4.6.1 because that's the lowest version that supports the netstandard.dll shim assemblies, so it has the same support limitation there as PowerShell Editor Services.

The workaround is to install .NET 4.6.1.

@daxian-dbw may be able to address whether any other fixes are possible, or whether it's possible to fail in a more informative way when this occurs. [Such a check is attempted in PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices/blob/6e3fa17fd5bc3bf8dd1aa187acb062580edef693/src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs#L231-L251).

**Comment by ThomasNieto** [comment]
@rjmholt have any idea why the .NET Version check didn't fail on module import?

```
DotNetFrameworkVersion = '4.6.1'
```

**Comment by rjmholt** [comment]
> @rjmholt have any idea why the .NET Version check didn't fail on module import?

Which version check do you mean? As far as I know PSRL does not check the .NET version, but I could be wrong since I'm not totally familiar with the codebase.

Could you elaborate on what your quote block is referring to here?

**Comment by daxian-dbw** [comment]
> DotNetFrameworkVersion = '4.6.1'

Yeah, ☝️ same question that I was about to post ... PSReadLine.psd1 has this setting in place and Import-Module should fail the importing and write out the informative message. I will need to check on a 2012R2 myself
See https://www.powershellgallery.com/packages/PSReadLine/2.1.0-beta1/Content/PSReadLine.psd1

**Comment by ThomasNieto** [comment]
@rjmholt the quoted block is from the module manifest. Import-Module should throw when importing a module when any requirements fail to pass.

**Comment by rjmholt** [comment]
Ah, yes PowerShell [doesn't actually verify that requirement](https://github.com/PowerShell/PowerShell/blob/b7c66ab3ef584956a2872856ee8b351784f522d9/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L1885-L1893).

**Comment by daxian-dbw** [comment]
@rjmholt That's pwsh, but I think @ThomasNieto was using Windows PowerShell, which should do the right check.

**Comment by rjmholt** [comment]
Oh I assumed it would work the same. If we expect that to work, that's strange that it hasn't

**Comment by daxian-dbw** [comment]
I looked into this issue a bit more this morning, and it turns out it's a bug in Windows PowerShell.
The method that checks for .NET Framework version has this snip of code:
```c#
if (checkVersion > PsUtils.FrameworkRegistryInstallation.KnownHighestNetFrameworkVersion)
{
    isSupported = true;
    higherThanKnownHighestVersion = true;
}
```
and guess what value does `KnownHighestNetFrameworkVersion` hold?
```c#
// .NET 4.5 is the highest known .NET version for PowerShell 3.0
internal static Version KnownHighestNetFrameworkVersion = new Version(4,5);
```
That value hasn't been changed since Windows 8 ... therefore, for a version greater than 4.5, the check method just believes it's supported, and only write out an verbose message when importing the module:
```none
PS:33> Import-Module .\abc.psd1 -Force -Verbose
VERBOSE: Loading module from path 'C:\arena\tmp\modules\abc\abc.psd1'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.9.0 because it is not included in the list of permitted versions.
VERBOSE: Loading module from path 'C:\arena\tmp\modules\abc\abc.psm1'.
```
I will move this issue to PowerShell repo, and see how we should proceed with it.

**Comment by daxian-dbw** [comment]
@ThomasNieto I opened a bug for this to Windows PowerShell internally, and the team that is maintaining Windows PowerShell will triage the bug. Given that, I will close this issue.
