### ISSUE TITLE
coding runs okay but follow this report with red letter that i should report this bug, how to erage this?

### ISSUE THREAD

**Issue by estelelenath** [PowerShell/PSReadLine#1610]
Space c d Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ C h a e b e o m Ctrl+Alt+\ D e s k t o p Ctrl+Alt+\ P y t h o n w o r k s p a c e ' ; Space & Space ' C : Ctrl+Alt+\ P y t h o n 3 8 Ctrl+Alt+\ p y t h o n . e x e ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ C h a e b e o m Ctrl+Alt+\ . v s c o d e Ctrl+Alt+\ e x t e n s i o n s Ctrl+Alt+\ m s - p y t h o 
n . p y t h o n - 2 0 2 0 . 5 . 8 6 8 0 6 Ctrl+Alt+\ p y t h o n F i l e s Ctrl+Alt+\ l i b Ctrl+Alt+\ p y t h o n Ctrl+Alt+\ d e b u g p y Ctrl+Alt+\ n o _ w h e e l s Ctrl+Alt+\ d e b u g p y

**Comment by daxian-dbw** [comment]
@estelelenath You don't have the exception message and stack trace part pasted here, so I don't know what the issue is. However, it's likely that the issue was fixed already if you are using an old version of PSReadLine. Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
