### ISSUE TITLE
Delete argument from command

### ISSUE THREAD

**Issue by nu8** [PowerShell/PSReadLine#1614]
If I have a commandline like this:

    sunday.exe monday tuesday-wednesday

I would like to delete to the last space, or essentially the last argument. I tried `Ctrl + Backspace`, but it deletes only to the first hyphen. Is this possible?

**Comment by daxian-dbw** [comment]
The word delimiters are configurable via `Set-PSReadLineOption -WordDelimiters`. You can remove the hyphen characters to make it delete to the last space.

**Comment by lzybkr** [comment]
Alternatively, you can use PowerShell's notion of a token:
```
Set-PSReadLineKeyHandler -Key Ctrl+Backspace -Function ShellBackwardKillWord
```

For a more complete list of suggested functions, see [the sample profile](https://github.com/PowerShell/PSReadLine/blob/fd9980642ce7943510dc65ea974d45faa4c900af/PSReadLine/SamplePSReadLineProfile.ps1#L104) which rebinds the default word movement bindings in Emacs mode to work on shell words instead of using the word delimiters.
