### ISSUE TITLE
some key binding does not work

### ISSUE THREAD

**Issue by kayasax** [PowerShell/PSReadLine#168]
I'm running a french version of windows 7 x64 and have notice the following bindings does not work with _windows_ edit mode : 

`Alt+.` (YankLastArg) (I've also tried Alt+; )
`Ctrl+Alt+Shift+?` (ShowKeyBindings)
`Alt+/`                (WhatIsKey)

is it because i'm running a non english version of windows?

**Comment by lzybkr** [comment]
I believe this is fixed in #561.

I'll publish a pre-release version to the PowerShell Gallery as soon as they support pre-releases.

If you'd like to try a fix before that, you can build the lastest yourself from the master branch, or 
grab a build from AppVeyor like this [one](https://ci.appveyor.com/api/buildjobs/ust6h6k216i5gm81/artifacts/bin%2FRelease%2FPSReadline.zip).

Note the version number is now 2.0, so be sure to copy the contents to <your module dir>\PSReadLine\2.0.

**Comment by lzybkr** [comment]
I'll have an official prerelease build out next week if you want to verify this is fixed, otherwise you can grab a build out of appveyor [here](https://ci.appveyor.com/project/lzybkr/psreadline).
