### ISSUE TITLE
Can we get a predictor based on help examples and mandatory parameters?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSReadLine#1817]
During the September community call, the demo showed a menu view which shows suggestions from plugins beyond the history, including a "AI" driven PowerShell Az recommender ...

There are two built-in sources of suggested command-lines that would be basically similar to what that recommender is doing, but much more universally useful. Once you can guess which command I'm typing, you can pre-populate command lines from the **help examples** or from the **parameter set syntax blocks**. I think it would be great to ship each of those as a named source, so like you showed a `[History]` source we could also have `[Help]` (or `[Get-Help]` or `[Help -Example]`) and `[Syntax]` (or `[Get-Command -Syntax]`).

These would be _huge_ for new users and for learning new commands!

**Comment by SeeminglyScience** [comment]
The design of the prediction subsystem doesn't allow for state based implementations (see [this PR comment thread](https://github.com/PowerShell/PowerShell/pull/13186#discussion_r456148007)).

I wonder if it would be possible to prebuild a static reference based on available modules.  Not sure how consistent that would feel though

**Comment by daxian-dbw** [comment]
The prediction subsystem stays experimental and is subject to change. We will need to think about how to converge the tab completion and the prediction, to get a more consistent intellisense experience.

**Comment by TheTaylorLee** [comment]
This would be an excellent feature to have. I've been looking for documentation to ad intellisense to my own modules and this would make it much more simple.

**Comment by StevenBucher98** [comment]
Tab completion has been incorporated in the [Completion Predictor](https://www.powershellgallery.com/packages/CompletionPredictor/0.1.1) we have published. I remember one community member was working on a predictor to incorporate help examples in predictions but the name of it escapes me

**Comment by daxian-dbw** [comment]
The [CompletionPredictor](https://github.com/PowerShell/CompletionPredictor) utilize the tab completion to provide prediction results for parameters, variables, members, type names, and some arguments. It syncs states of the default session Runspace so it can reflect all changes to the default Runspace. It doesn't provide prediction results for command names because the command name completion usually takes too long (more than the default prediction timeout).

The `CompletionPredictor` can be used as an example for anyone who want to implement a predictor based on the help content. We also have the document about how to create a command-line predictor: https://learn.microsoft.com/powershell/scripting/dev-cross-plat/create-cmdline-predictor?view=powershell-7.3
