### ISSUE TITLE
Windows bindings for ReverseSearchHistory and ForwardSearchHistory

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#186]
I would like to suggest two changes here.  First the name of these two commands are confusing vis-a-vie HistorySearchBackward and HistorySearchForward.  Perhaps you rename these commands to HistoryIncrementalSearchBacward/Forward.  The more important change IMO is to use different keybindings a bit more friendly to Windows users and not emacs users.  There's already an emacs mode for those folks.  

I suggest this mapping as the default

```
Set-PSReadlineKeyHandler -Chord Ctrl+i              -Function ReverseSearchHistory
Set-PSReadlineKeyHandler -Chord Ctrl+Shift+i        -Function ForwardSearchHistory
```

This nicely lines up with Visual Studio incremental search feature Ctrl+i and Ctrl+Shift+i.  Another alternative is to use Ctrl+F and Ctrl+Shift+F.  I would prefer either one over Ctrl+R/S but I like that this command and key bindings behave very similarly to the ones in VS's incremental search.

**Comment by lzybkr** [comment]
Function names typically follow bash where possible, so for example, bash has history-search-forward, and because I'm lazy and use C# reflection for binding function names, that is HistorySearchForward.

Of course it's confusing in bash, the incremental search is reverse-history-search, and somehow I didn't match that.  I remember struggling with my decision, wanting less confusing names here, in fact I think I had different names at one point.

I like the idea of using Ctrl+i.  Ctrl+f will eventually be used to search the buffer, not history.

**Comment by lzybkr** [comment]
We ended up with `Ctrl+r` as a default binding for `ReverseSearchHistory`, so I don't think this makes sense anymore.
