### ISSUE TITLE
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。

### ISSUE THREAD

**Issue by alpha87** [PowerShell/PSReadLine#1917]
上 1 个密钥:
 UpArrow

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   在 Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
@alpha87 You didn't provide PSReadLine version information so it's not clear whether this is a new issue. Most likely, this issue was already fixed (see #1306). Please upgrade to the [2.1.0-rc1 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0-rc1) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
