### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ifanwtf** [PowerShell/PSReadLine#1919]
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
tualTerminal.set_CursorLeft(Int32 value)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0-rc1 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0-rc1) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
