### ISSUE TITLE
Programmable auto-completion

### ISSUE THREAD

**Issue by jhclark** [PowerShell/PSReadLine#194]
Bash/zsh have the concept of programmable auto-completion (http://tldp.org/LDP/abs/html/tabexpansion.html).

Lately, I've found myself wanting this in Windows land:
- My group at work has a standard library for parsing command line arguments and config files (similar to boost program options, but not), a large number of our binaries use it.
- For any of those executables, I'd love to be able to get completion via PSReadline
- It would be easy to do ask the executable to dump its known flags when passed something like --DumpOpts and PSReadline (or a PSReadline plug-in that the user writes) could just be expecting a standard format to parse

The reason this seems to be a no-go for vanilla PowerShell is that it's so focused on Cmdlets (where parameter definition has many lovely features) that it provides minimal features for interacting with native executables.

Note: I've done something similar in a powershell script with dynamic options, but writing a powershell wrapper around dozens of executables doesn't seem feasible.

Questions:
- Is there already a way of doing this in PowerShell? (I'm fairly confident the answer is no, but you surprise me sometimes)
- Is there already a way of doing this with PSReadline?
- If not, would a plug-in architecture/callback make sense? (e.g. List<PSReadlineParameterObject> GetParameters(string cmdLineSoFar); )

**Comment by lzybkr** [comment]
Yes, see https://github.com/lzybkr/TabExpansionPlusPlus

See https://github.com/lzybkr/TabExpansionPlusPlus/blob/master/WindowsExe.ArgumentCompleters.ps1 for some good examples of how completion is done for exes.

Note that TabExpansion++ has two ways to register a completer.  There aren't many examples, but I recommend using the cmdlet Register-ArgumentCompleter as that cmdlet is an excellent candidate to appear in a future version of PowerShell where as the attributed function approach, which most of the examples use, is probably not going into the product because it requires too much parsing and scanning when loading the module.

**Comment by jhclark** [comment]
Remind me to buy you a beer sometime.

**Comment by jhclark** [comment]
Follow-up question at https://github.com/lzybkr/TabExpansionPlusPlus/issues/32
