### ISSUE TITLE
problem with python

### ISSUE THREAD

**Issue by adrianmankiewicz** [PowerShell/PSReadLine#1981]
Hi today i was that problem. What i should do? It was warking
![Zrzut ekranu 2020-11-24 114733](https://user-images.githubusercontent.com/72507038/100084295-e0dd7700-2e4a-11eb-9461-052663e354ca.jpg)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
