### ISSUE TITLE
New issue with Windows PowerShell

### ISSUE THREAD

**Issue by paolopiano1997** [PowerShell/PSReadLine#1986]
While I was typing my git commit command, without pressing enter, this issue appeared (Italian language):

Ultimi 33 tasti:
 g i t Space c o m m i t Space - m Space " Ctrl+c UpArrow DownArrow g i t Space c o m m i t Space - m Space "

Eccezione:
System.ArgumentOutOfRangeException: Il valore deve essere maggiore o uguale a zero e minore della grandezza del buffer della console in tale dimensione.
Nome parametro: left
Valore effettivo: -1.
   in System.Console.SetCursorPosition(Int32 left, Int32 top)
   in Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   in Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   in Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   in Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   in Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   in Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
