### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Umarabd** [PowerShell/PSReadLine#1999]
Hello sir, my name is umarabd.. i am a begineer in phyton.

when i run a phyton with visual basic code there are somebug that i didnt now why it happens

the command said to contact you from github.

so, i attach some field about the bug. 

[bug.txt](https://github.com/PowerShell/PSReadLine/files/5613190/bug.txt)
thank you

**Comment by hassaanmunir007** [comment]
Try to update PSReadLine. Open up PowerShell as administrator and copy/paste this command,
Install-Module -Name PSReadLine -RequiredVersion 2.1.0

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
