### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by shivamjjha** [PowerShell/PSReadLine#2027]
I encountered following issue while typing into terminal:
I also increase the integrated VS Code terminal buffer size from `1000` to `10000` and tried closing and re-starting the terminal. But the issue still exists

![Screenshot 2020-12-07 211006](https://user-images.githubusercontent.com/44032634/101371893-4ad93000-38d1-11eb-83d2-7fbaf0a845d9.jpg)

This issue comes and goes randomly

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
