### ISSUE TITLE
Last 200 Keys:  a i l s I n E x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ H a r s h a d \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ 8 d 4 e 4 d 5 1 1 c 9 6 9 f 7 8 3 8 6 e 9 4 2 3 e 8 9 7 c 1 f 5 \ r e d h a t . j a v a \ j d t _ w s \ D S A _ 6 9 a f d 6 8 2 \ b i n ' Space ' S o r t i n g A r r ' Space Enter

### ISSUE THREAD

**Issue by Harshad1999** [PowerShell/PSReadLine#2055]
![image](https://user-images.githubusercontent.com/53564757/102570440-587e8900-410d-11eb-8095-9c138d11d494.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
