### ISSUE TITLE
add auto indentation in multiline

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PSReadLine#2065]
## add auto indentation in multiline mode

PSReadline is great but i will be great to add a functionality to auto indent in multilne code and remove '>>'

```
PS C:\> if($true) {
>> echo $true
>> } else {
>> echo $false
>> }
True
PS C:\>
```

in other shell like fish the display is more elegant and it auto indent and auto inindent automatically like an  editor

![Capture](https://user-images.githubusercontent.com/36144546/102716060-2f393680-428e-11eb-82bb-0194e4904b4e.PNG)

**Comment by theJasonHelmick** [comment]
Thanks for the idea - My experience has been that people like to choose their editor for quick shell functions such as vi, vim, nano etc and use richer editors (like Vscode) for more complicated automation.  Because of this, Improving the inline experience (which really isn't good as an editor) hasn't been a focus of mine.  Under what scenarios outside of a quick a dirty function would this be useful?
