### ISSUE TITLE
System.ArgumentOutOfRangeException: 

### ISSUE THREAD

**Issue by Dahkenangnon** [PowerShell/PSReadLine#2071]
Usually, i get this erro when opening my terminal on windows 10:

Oups, un problème s'est produit. Signalez ce bogue avec les détails ci-dessous.
Signaler sur GitHub : https://github.com/lzybkr/PSReadLine/issues/new     
-----------------------------------------------------------------------   
Dernières 1 touches :
 Ctrl+l

Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
La valeur réelle était -2.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
