### ISSUE TITLE
System.ArgumentOutOfRangeException    it said to report this bug here.

### ISSUE THREAD

**Issue by p-m986** [PowerShell/PSReadLine#2104]
![Screenshot (150)](https://user-images.githubusercontent.com/77034913/103721783-95df8380-4ff4-11eb-8301-5ffe4f6c7e2c.png)

I dont have a vid of it when it happened but I have recorded the after terminal so I can share it if required.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
