### ISSUE TITLE
VS Code Bug, How to fix it?

### ISSUE THREAD

**Issue by Soplanz** [PowerShell/PSReadLine#2141]
![Screenshot (97)](https://user-images.githubusercontent.com/70798003/104983922-55debe80-5a40-11eb-8e47-c3c0fe9b108a.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
