### ISSUE TITLE
I can't create a database in vs code.

### ISSUE THREAD

**Issue by terapatpoolperm** [PowerShell/PSReadLine#2199]
<img width="960" alt="error in week7_954240" src="https://user-images.githubusercontent.com/77433001/107342668-15300d80-6af3-11eb-86d9-9137dcfe9d87.png">

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by terapatpoolperm** [comment]
how to install?

ในวันที่ พ. 10 ก.พ. 2021 เวลา 01:50 Dongbo Wang <notifications@github.com>
เขียนว่า:
