### ISSUE TITLE
Update-Help in Powershell 5.1 Fails

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#2285]
[Duplicate that may have been fixed, but is now broken again](https://github.com/PowerShell/PSReadLine/issues/566)

## Environment
PS version: 5.1.18362.1171
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000

## Exception report
N/A

## Steps to reproduce
Run Update-Help from an elevated (Administrator) PS window.

## Expected behavior
Expected the help information for the modules to be updated.

## Actual behavior
Various errors. See screenshots.

![image](https://user-images.githubusercontent.com/47870566/110529575-47bb2f00-80ce-11eb-9fc6-47cfe8b9345e.png)

**Comment by daxian-dbw** [comment]
@tboring-hss-sbcounty-gov You may just need to rename the name of your "PSReadline" module folder to "PSReadLine" (be noted on the lower-case `l` vs. capital `L`). Here is a blog talking about this issue: https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/

Give it a try and see if that resolve the issue.

**Comment by daxian-dbw** [comment]
I checked with @sdwheeler this afternoon and realized that `Update-Help -Module PSReadLine` is broken in Windows PowerShell 5.1. This is because the help content was moved from downloadable center (DLC) to Azure Blob. The links to DLC was case-insensitive but links to Azure Blob is case-sensitive. The help content for the PSReadLine module was also moved from using `PSReadline` to `PSReadLine` (be noted on the `l` to `L` change), and thus after moving to Azure Blob, the link became broken.

Here is the workaround:
1. Close all powershell.exe processes. Then rename the `PSReadline` module folder name to `PSReadLine`.
2. Open an powershell.exe session in Administrator privilege.
3. Run `Remove-Module PSReadLine` to remove the auto-loaded PSReadLine module (it's always loaded with the name `PSReadline`).
4. Run `Import-Module PSReadLine` (literally use `PSReadLine` without change).
5. Then run `Update-Help -Module PSReadLine -Force`

I verified this workaround locally. Please let us know if it works for you.

**Comment by daxian-dbw** [comment]
We have a blog published to make this workaround easier to discover: https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

**Comment by tboring-hss-sbcounty-gov** [comment]
This issue is not a question, therefore marking it as "Question Answered" is invalid. This issue is a documented bug in Powershell 5.1. And the solution is to publish a blog article, and have server admins manually run through those steps on each machine needing the fix? I expected a better solution from Microsoft. Push an update for machines running Powershell 5.1.

**Comment by ghost** [comment]
This issue is not a question, therefore marking it as "Question Answered" is invalid. This issue is several errors occurring in PowerShell 5.1. That blog article only addresses one of the errors. What about the others? Is there a blog entry on how to fix each of those?

![image](https://user-images.githubusercontent.com/47870566/110829814-64ca3c00-824d-11eb-8d12-e9e3ce2c1773.png)

**Comment by sdwheeler** [comment]
Those other modules are broken. We are working with the module owners to find a solution.
