### ISSUE TITLE
VScode 1.54.1 Powershell Issue

### ISSUE THREAD

**Issue by pshubham1** [PowerShell/PSReadLine#2299]
I started getting this error when I run my code. I don't know how it comes about; it appears even when I'm very simple code which should work otherwise.

Any help would be appreciated.

![image](https://user-images.githubusercontent.com/80494566/110873727-4b1b0a00-82ca-11eb-8bac-fcf9b4c825d0.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
