### ISSUE TITLE
PredictionSource Will Not Stay After Restart

### ISSUE THREAD

**Issue by YuriySamorodov** [PowerShell/PSReadLine#2366]
## Environment

```none
PS version: 7.1.1
PSReadline version: 2.2.0-beta1
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.1.0
HostName: ConsoleHost
BufferWidth: 122
BufferHeight: 9001
```

## Exception report
No exceptions

## Steps to reproduce

1. Open New PowerShell console
2. Try typing command that is in History. No prediction will be available
3. Run `Set-PSReadLineOption -PredictionSource History` command
4. Run `( Get-PSReadLineOption ).PredictionSource`. It should return "History":
![image](https://user-images.githubusercontent.com/5260172/114954455-4b776980-9e63-11eb-8165-2e696eb2e55e.png)
5. Try typing some command from the past one more time. PSReadline will provide some predictions
6. Close PowerShell console
7. Repeat steps 1-2
8. Open New PowerShell console
9. Run `( Get-PSReadLineOption ).PredictionSource`. It will return "None" this time:
![image](https://user-images.githubusercontent.com/5260172/114954577-95604f80-9e63-11eb-9377-3a12114f6f4d.png)

## Expected behavior
PSReadline should keep PredictionSource after consoler restart

## Actual behavior
PSReadline does not keep PredictionSource value after console restart

**Comment by rkeithhill** [comment]
This is the expected behavior.  Setting a PSReadLineOption persists just for the current session.  This is the case for most modules that have settings. 

The way you make module settings available across sessions is to configure them in your profile script.   Run `notepad $profile` or `notepad $HOME\Documents\PowerShell\profile.ps1` (for all hosts) and add that line to this script and save it. Note: if that file doesn't exist, then create it.  Then, whenever you open PowerShell, this setting will be available.  This is also how you can pre-load certain modules in your session like `posh-git`.

**Comment by YuriySamorodov** [comment]
Thanks @rkeithhill, much appreciated!
