### ISSUE TITLE
I just pressed up

### ISSUE THREAD

**Issue by OSU-GUY** [PowerShell/PSReadLine#2393]
I have been having fun with osu danser, and today i just pressed the up  arrow on the console and this came up, so i reported it
![2021-04-24 (5)](https://user-images.githubusercontent.com/83136149/115968806-7af83700-a531-11eb-93da-0e552f487df2.png)
I don't think anything is broken, just here because the error told me to report it
P.S If you are wondering what i was doing before this happened, i was making the cursor danser play 100* maps, wich crashed the program
BTW i am bad at english

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
