### ISSUE TITLE
System.ArgumentOutOfRangeException: 値には0以上で、コンソールの次元のバッファーサイズ未満を指定しなければなりません。

### ISSUE THREAD

**Issue by ogihara2010** [PowerShell/PSReadLine#2396]
パラメーター名：left
実際の値は -1 です。
　場所　System.Console.SetCursorPosition(Int32 left, Int32 top)
　場所　Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int 32 value)
　場所　Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
　場所　Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
　場所　Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
　場所　Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
　場所　Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
　場所　Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
　場所　Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
　場所　Microsoft.PowerShell.PSConsoleReadLine.

**Comment by daxian-dbw** [comment]
@ogihara2010 It's not clear what version of PSReadLine you were using, but likely to be a pretty old one (2.0.0-beta2 or prior). Many similar issues were fixed in the newer versions, so please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
