### ISSUE TITLE
bug oops, 

### ISSUE THREAD

**Issue by royavatar** [PowerShell/PSReadLine#2409]
got this 
PS C:\WINDOWS\system32>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
![git hub error  2021-04-29 134906](https://user-images.githubusercontent.com/83408242/116554296-edcb2e80-a8f2-11eb-9b7e-b6d591cc4fd0.jpg)

hi trying to get  IF detection of objects to work with my windows 10 pc, and 
Agentdvr software. using help doc below.
https://docs.deepstack.cc/using-deepstack-with-nvidia-gpus/index.html

**Comment by royavatar** [comment]
hi second error after hitting enter.
![image](https://user-images.githubusercontent.com/83408242/116555403-40f1b100-a8f4-11eb-8669-51fef0aa1533.png)
regrads roy

**Comment by royavatar** [comment]
closed by mistake, first time hear,

**Comment by daxian-dbw** [comment]
@royavatar you were using a pretty old version of PSReadLine (2.0.0-beta2 or prior), and it's likely that the issue was fixed in a newer version.
Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by daxian-dbw** [comment]
As for your second error, you tried to run bash scripts in Windows PowerShell, which won't work.
