### ISSUE TITLE
about_PSReadline.help.txt is not UTF-8. 

### ISSUE THREAD

**Issue by juneb** [PowerShell/PSReadLine#254]
You might want to fix the non-compliant help file. :)

**Comment by lzybkr** [comment]
Could you elaborate on why a file must be UTF8?

If the file is pure ascii, there's no ambiguity w.r.t. code pages, and PowerShell handles the help file just fine, so it really doesn't matter from my point of view.

**Comment by juneb** [comment]
It's a standard, Jason, and tools that post-process the help files rely on that encoding guarantee. As to the rationale for choosing that particular encoding, you'd have to ask DanielHa, Lee or Nana.

**Comment by lzybkr** [comment]
June, I'm well aware of standards - I do work on parsers for a living.  ASCII is also a standard, and in my experience, there are more tools that handle ASCII but not UTF8 than vice versa.

At any rate, I'll change the encoding if somebody tells me those post-processing tools aren't working, otherwise there doesn't seem to be a point.

**Comment by rkeithhill** [comment]
But ASCII, even without the UTF8 BOM, is still valid UTF8.  From Wikipedia https://en.wikipedia.org/wiki/UTF-8 :

> The first 128 characters of Unicode, which correspond one-to-one with ASCII, are encoded using a single octet with the same binary value as ASCII, making valid ASCII text valid UTF-8-encoded Unicode as well.

Could it be that some tools are requiring a UTF8 BOM when they need not?

**Comment by juneb** [comment]
Keith, to test file encoding, I'm using [https://gist.github.com/jpoehls/2406504]().

**Comment by rkeithhill** [comment]
@juneb Handy but the Get-FileEncoding command implementation is a bit naive.  Just because a file doesn't have a BOM, it does not mean that it is an ASCII file.  See this article by Raymond Chen on the issues related to detecting a text file's encoding: http://blogs.msdn.com/b/oldnewthing/archive/2007/04/17/2158334.aspx
