### ISSUE TITLE
Bug in vscode with pylance

### ISSUE THREAD

**Issue by ZJsheep** [PowerShell/PSReadLine#2582]
![image](https://user-images.githubusercontent.com/73184640/122082154-56825200-ce32-11eb-9f69-1a671a624e72.png)
It appeared when I am testing a Python programme in VScode with Pylance.
I guess that it should be related to the fact that I am outputing a lot of data in the console then?
Seems that the so-called 'left' variable has run out of bound of int32?
OS version: Windows 10 19042.1052
VScode version: 1.57.0
PowerShell version: 5.1.19041.1023

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
