### ISSUE TITLE
Error while running a python file on vscdoe

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#2584]
I pressed CTRL + F5 to run my code and i got these errors. I hope it helps you. 

[Error.txt](https://github.com/PowerShell/PSReadLine/files/6657612/Error.txt)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
