### ISSUE TITLE
powershell

### ISSUE THREAD

**Issue by vishranth20** [PowerShell/PSReadLine#2619]
![image](https://user-images.githubusercontent.com/75408252/123497604-1732dd00-d64c-11eb-8678-dd6ccdf7ca0b.png)

HELP ME FIX THIS

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
