### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below. [ArgumentOutOfRangeException]

### ISSUE THREAD

**Issue by frevds** [PowerShell/PSReadLine#2629]
Please see the console screenshot (in VSC): 
![image](https://user-images.githubusercontent.com/5341447/123942018-07dcc800-d99b-11eb-8386-5c413fed1d3f.png)

I attempted to scroll through previous (multi-line) commands in the history but it did not work (arriving at the top did not go back in the history). Pressing ESC then printed this error.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
