### ISSUE TITLE
[URGENT] Discord Bot Error

### ISSUE THREAD

**Issue by Kanghyunroe** [PowerShell/PSReadLine#2670]
Hi I'm getting this error while trying to make a discord bot. Please help. I'm using python. 
![Screenshot 2021-07-13 133509](https://user-images.githubusercontent.com/80022724/125522359-706e0c54-51b0-44b2-af8a-06ad244493e9.png)
![Screenshot 2021-07-13 131926](https://user-images.githubusercontent.com/80022724/125522361-49f5c625-300d-453e-8da3-591746612252.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
