### ISSUE TITLE
Do you guys know how to fix this terminal bug in visual studio code ?

### ISSUE THREAD

**Issue by Novand21** [PowerShell/PSReadLine#2699]
https://user-images.githubusercontent.com/87837171/126724636-1c089e8c-85a5-4d52-8235-de949e3b9878.png

**Comment by The-Coder-x** [comment]
This same thing happened to me many times. 
I even re-installed my vs code, but it appears again and again.

**Comment by daxian-dbw** [comment]
Please update the PSReadLine module. The version of PSReadLine you are using is very old.

This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
