### ISSUE TITLE
Request for better key handler defaults

### ISSUE THREAD

**Issue by ratijas** [PowerShell/PSReadLine#2711]
I'd like PSReadLine to have better key handlers out of the box.

## Description of the new feature/enhancement

I really like that out of the box (even without PSReadLine, I guess?) PowerShell lets you navigate and delete words with Ctrl key modifier.

I also like to travel through history with `Ctrl+P` / `Ctrl+N`.

`Ctrl+P` / `Ctrl+N` only work in emacs mode, which also disables Ctrl+keys navigation without any reason and alternative: Ctrl+arrows stops doing anything, and Ctrl+Backspace deletes one character as if Ctrl was not held at all.

Can't we combine the best of both worlds into some sane defaults which would require zero-configuration?

## Proposed technical implementation details (optional)

Either add Ctrl+P/N history navigation to the default (Windows) mode, or don't remove Ctrl+keys text navigation and editing from Emacs mode. Or maybe both.

**Comment by daxian-dbw** [comment]
The default key bindings are supposed to target each edit mode. For example, `ctrl+p` and `ctrl+n` are moving up/down in many Unix shells, but it's likely rarely known by many Windows users. Similarly, `alt+backspace` is deleting a word backward in many Unix shells, instead of `ctrl+backspace`. We don't plan to mix them up in default key bindings, but you can always configure the key bindings by `Set-PSReadLineKeyHandler` in your PowerShell profile to make them work the best for you.

**Comment by ratijas** [comment]
> `alt+backspace` is deleting a word backward in many Unix shells

Wait, what? That came as a surprise.

> make them work the best for you

The thing that works best for me (and for most users) is zero-conf. Which is to say, good defaults taking care of everything out-of-the-box.

I did have thousands-lines .vimrc in past. No, I'm not doing that anymore. That's insane and unmaintainable.

I can understand that doing nothing is the preferred way for maintainers to "resolve" an issue. But, I mean, come on… If keys are not bound to anything, why not bind them to something useful and widely(?) accepted?
