### ISSUE TITLE
When i run code it works but lot uneeded stuff in terminal 

### ISSUE THREAD

**Issue by Exido-Rio** [PowerShell/PSReadLine#2746]
I dont know what kind of error it is but cheak that picture linked 

![xzzzzzzzzz](https://user-images.githubusercontent.com/76099242/129188974-ce9364d7-b683-4236-bcfa-5d537c46c554.png)
![zxxx2](https://user-images.githubusercontent.com/76099242/129189194-38e878b7-d574-41fb-8300-6eccd68060d8.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
