### ISSUE TITLE
ParserError from provided sample script

### ISSUE THREAD

**Issue by symisz** [PowerShell/PSReadLine#2747]
PS version: 7.1.3
PSReadline version: 2.2.0-beta3
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.3.0
HostName: ConsoleHost
BufferWidth: 271
BufferHeight: 17

---

Using the sample script from
https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/SamplePSReadLineProfile.ps1
starting on line 220: Set-PSReadLineKeyHandler -Key '(','{','[' `
Each of these characters { and [ in that line will cause a multiline hash table unable to render.

## Steps to reproduce

Copy the script https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/SamplePSReadLineProfile.ps1
from line 220 to 251 to your PowerShell $profile.
then execute a hash table:

```    
[hashtable]$hash = @{ 
  Number = 1
  Shape = "Square"
  Color = "Blue"
}
```

Resulting in a ParseError

**Comment by daxian-dbw** [comment]
@symisz Yeah, you will see the parsing errors if you paste that hash table script by **right clicking**. That's a by design behavior due to how right clicking works. By right clicking, the copied text is sent to the terminal/console just like typing it character by character, and there is no way to differentiate that from a user's typing (well, maybe there is, by measuring the time interval between receiving the keystrokes, but won't be reliable). Hence, the key binding will kick in and in this case it will close the open braces, and that would cause the parsing errors.

In PowerShell, it's recommended to use <kbd>Ctrl+v</kbd> to paste the copied text. That hash table script will work fine if you use <kbd>Ctrl+v</kbd> instead.
