### ISSUE TITLE
Have some bug but it dont tell in the terminal

### ISSUE THREAD

**Issue by Thiem52209** [PowerShell/PSReadLine#2752]
![image](https://user-images.githubusercontent.com/87347059/129362245-d5c244cd-d7d3-478b-9ca5-d672aa8eb13a.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
