### ISSUE TITLE
"Command x cannot be found" displaying incorrectly

### ISSUE THREAD

**Issue by bdukes** [PowerShell/PSReadLine#278]
Using v1.0.0.13, I'm consistently getting the error that a command can't be found on the first time that I try to run that command in a session.  If I force the execution of the command, it works, and then I don't get the warning when executing the command later on in the same session.  I'm able to <kbd>tab</kbd> complete the name of the command, but get the error when hitting <kbd>enter</kbd>. This happens for commands that I have in a custom module that I include in my profile (https://github.com/bdukes/PowerShell-Profile/blob/master/Modules/DNNing/DNNing.psm1), but doesn't happen for other modules that I include in the same way.

Let me know if there's any testing/logging/debugging I can do on my end to track it down for you.  Thanks!

**Comment by lzybkr** [comment]
The problem is in the function ValidateAndAcceptLine (or more likely in the PowerShell engine itself.)  As a workaround, you can change the binding to Enter, this is how PSReadline ships in Win10:

```
Set-PSReadlineKeyHandler -Key Enter -Function AcceptLine
```

As an alternative, you could try creating a module manifest for your module and put the exported commands in the psd1 - that might help the PowerShell engine figure out which commands are available in that module before the module gets loaded.

**Comment by lzybkr** [comment]
I just tried this with your module and it repros only because I don't have the dependent modules installed. If I remove the `#requires`, the command runs.

I'm not sure if this addresses your problem, but it's been a couple years, so maybe you don't even care anymore :)
