### ISSUE TITLE
Python Will Not Run Any File; System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by SweetReap** [PowerShell/PSReadLine#2830]
Hello, I am trying to run some python code to refresh on algorithms, but it gives me this error:
`Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.`

AND 

` /Python39/python.exe : The term '/Python39/python.exe' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1 + /Python39/python.exe d:/Games/Development/python/Intermediate/Algos/L...+~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          :
    ObjectNotFound: (/Python
  39/python.exe:String) [],
  CommandNotFoundException
    + FullyQualifiedErrorId :
    CommandNotFoundException `

I tried reinstalling the python extension on VSCode, but it has not fixed this issue.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
