### ISSUE TITLE
how i fixed it ?

### ISSUE THREAD

**Issue by Iharys** [PowerShell/PSReadLine#2849]
![image](https://user-images.githubusercontent.com/80513394/133083062-ebd9fdc3-1647-4dcb-9343-3b6eac6ac089.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
