### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by prakriti06** [PowerShell/PSReadLine#2852]
Unable to run any code of C/C++.
shows an error "Something went wrong".
![image](https://user-images.githubusercontent.com/65858894/133273638-f5d686c4-0c67-46d0-8435-48b382267004.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
