### ISSUE TITLE
Error on vscode terminal

### ISSUE THREAD

**Issue by mohamednafann** [PowerShell/PSReadLine#2855]
This error happened when I split my terminal and run docker container in first one and stop in the first two.

![image](https://user-images.githubusercontent.com/90103335/133437883-535b80b9-1f73-401d-bc9d-48a82e6bb70b.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
