### ISSUE TITLE
IO Exception on "change directory" command

### ISSUE THREAD

**Issue by higorcoimbra** [PowerShell/PSReadLine#2856]
Greetings!

As I was trying to change directory on PowerShell, I thought it was already changed and hit "Ctrl + L" to clear the screen. Hence, I received the above message as an Exception:

![image](https://user-images.githubusercontent.com/17783727/133454480-c0ffa283-2d57-4c2a-b3d5-f90a238f4a00.png)

EDIT: I had to restart PowerShell, "Ctrl + L" keep returning the same Exception.

Reporting as instructed on the screen. Thanks!

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
