### ISSUE TITLE
Error pasting into command prompt

### ISSUE THREAD

**Issue by triynko** [PowerShell/PSReadLine#2868]
Still trying to get around that unexplainable 50 character paste limit (https://github.com/microsoft/terminal/issues/38#issuecomment-826395739:), and ran into this issue:

![image](https://user-images.githubusercontent.com/1005113/133861721-9a43d809-4239-4126-a5da-c7f489b4b1d3.png)

It's impossible to paste a full command into a "docker exec -it" console window. I can paste it into the console, but if I then copy it from the console and try to right click to paste it into that same console window after invoking Powershell, it shows that out of memory exception and asks me to report it.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
