### ISSUE TITLE
Is PSReadLine shipped with WMF 5.0 Production Preview (Windows 7)

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#287]
I just installed the WMF 5.0 Production Preview on Windows 7 and PSReadLine was not installed. Is it only shipped on Windows 10? If this is the case it's very confusing.

**Comment by lzybkr** [comment]
Yes, it was an intentional choice to ship PSReadline on Windows 10 but not in the WMF package for downlevel machines.  Fortunately, it's super easy to install after you've installed WMF5 because you have PowerShellGet installed with WMF5, so it's just:

```
Install-Module PSReadline
```

**Comment by gwojan** [comment]
@lzybkr Might you shed some light on why the decision was made?

I understand the ease of using the PSReadLine module from the PowerShell Gallery but I've noticed PowerShell 5.0 loads the module automatically whether I want it to or not.

I see on Windows 10 there is

``` PowerShell
[Microsoft.PowerShell.ConsoleShell]::UsePSReadline = $false
```

but it doesn't work on Windows 7. Because the module is always in use I'm not able to uninstall it -- any ideas?

Finally, I'm using the PSReadLine fork from @srdubya for the Vi support so I'm not really able to use PowerShellGet. Do you have any idea when that fork might actually make it into the published module?

**Comment by lzybkr** [comment]
I was not part of the decision making process, so I can't comment on the decision to not include PSReadline in WMF.

That line you reference from Win10 was in a preview build, but not the RTM version of Win10.

PSReadline is not loaded if PowerShell is started non-interactively, so you could do something like:

```
powershell -noprofile -command "Install-Module PSReadline"
```

or

```
powershell -noprofile -command "Update-Module PSReadline"
```

Updating on Win10 is also a little tricky because Update-Module doesn't actually work until it is first installed with Install-Module.  There is no reason to do either of these yet on Win10.  Hopefully I'll have some bugs fixed and a new release soon, then it will make sense.

vi support will come, I'm just not sure when.  PSReadline has turned into real work instead of a fun side project.  I have essentially no time allocated for it yet many bugs (not all reported on GitHub) that need to be fixed.

Each time I play with vi mode, I find a bug very quickly, so when I get serious about integrating it, I'll probably use it exclusively for a week or two before I decide it's ready.  That said - it looks really good right now.

**Comment by gwojan** [comment]
Actually I was playing with the WMF 5.0 Production Preview on Windows 7 and that's where I was having the issue of PSReadLine autoloading and always being in use. PSReadLine appears to load as one of the default modules once it's installed either via `Install-Module` or placing PSReadLine in `$env:PSModulePath`.

Thanks for the suggestions -- I'll give those a try although I can see `Update-Module` being a pain with any DLL based modules once the DLLs are loaded.

The latest builds of Vi mode have been very good for me. There are still some minor issues around delete commands deleting too much but no real showstoppers. Vi mode has been a real productivity boost for me having to jump between bash/zsh/PowerShell all day long. I'm hardly a Vi expert but PSReadLine + Vi support is awesome! :grinning:

**Comment by srdubya** [comment]
As far as I know, every reported issue flagged as vi-specific has been addressed.  Please submit defects for the problems you're seeing.

**Comment by gwojan** [comment]
@srdubya I lost my list... :frowning: But, it was a pretty short list. It's mainly just inconsistencies between PSReadLine+Vi and vim/gVim. I'll post more issues as I find them and can write up a repro.

**Comment by lzybkr** [comment]
I just fixed the last issue I hit.  I'll do more of that as I find the time.
