### ISSUE TITLE
Bug when launching a new Powershell instance with Start-Process and alternate credentials

### ISSUE THREAD

**Issue by bjaudon** [PowerShell/PSReadLine#288]
Originally, I opened a bug report for PowerShell with Microsoft Connect (https://connect.microsoft.com/PowerShell/Feedback/Details/1821747) about this issue, but I have since learned it is with the PSReadline module included with Windows 10, and possibly previous versions.

On Windows 10, from the PowerShell console when using the command "Start-Process powershell -Credential (Get-Credential) -PassThru", while specifying credentials other than those of the current login (eg. CONTOSO\user is currently logged in, and specified CONTOSO\admin in the Get-Credential), the new PowerShell process becomes unresponsive to keyboard commands until either A) enter is pressed in the parent window, or B) the parent window is closed. In the case of A, when the enter key is pressed, the new window will begin typing whatever was put into the window. At that time, the parent window goes unresponsive until the reverse is done.

A workaround is done by issuing Remove-Module PSReadline prior to running Start-Process. However, you cannot reload the module or the issue resumes.

**Comment by dogleft** [comment]
I just reproduced this on Win10  5.1.14393.2879 Thanks for noting the workaround, Bryan!
I reproed launching both powershell.exe and cmd.exe

PS peeps - my scenario is managing privileged credentials using Cyberark, and my module targets allowing admins to launch privileged processes without needing to know the underlying credentials. E,g, running mundane disk maintenance scripts interactively against domain controllers. I ran into this bug immediately. To the extent that you consider interactive admin important, please raise the priority of this bug.

I'll use the workaround for now, but it's ugly and makes for an inconvenient admin experience. E.g.
```
Remove-Module PSReadline
Start-Process $command -Credential $cred
Read-Host -prompt "Hit <enter> after you're done with the elevated console. Dont use this console until then."
Import-Module PSReadline
```

**Comment by jeffrson** [comment]
I came across this very same problem in powershell as well as powershell core.

Regarding the age of the issue - any news or roadmap how to fix?

**Comment by JamesLear92** [comment]
A work around is to use the .NET Diagnostics.Process class

            $Credential = Get-Credential
            $Process = [Diagnostics.Process]::new()
            $Process.StartInfo = [Diagnostics.ProcessStartInfo]::new()

            $Process.StartInfo.FileName = $PowerShellPath
            $Process.StartInfo.UseShellExecute = $false
            $Process.StartInfo.Arguments = ('-NoExit -ExecutionPolicy Bypass -Command ')
            $Process.StartInfo.Domain, $Process.StartInfo.Username = $Credential.UserName -Split '\\'
            $Process.StartInfo.Password = $Credential.Password
            $null = $Process.Start()

One thing to note is that the user account will have "c:\users\default" as it's $env:UserProfile path, so you'll need to create a folder called PowerShell in "C:\Users\Default\AppData\Roaming\Microsoft\Windows"
then you'll need to provide the user account read/write permissions, I just gave authenticated users RW because I'll be using this for a bunch of different accounts.

**Comment by StewartRyanSony** [comment]
Any update on this? I just ran into this same problem both in PowerShell and pwsh.

**Comment by dwillis77** [comment]
Just curious - 2 years after the last comment - do we have any update on when this might be fixed yet? This issue looks like it goes back to at least 2015, and I imagine this scenario is one that a fair amount of people might find themselves in. Plus, its still an issue in the latest PS v7.

Any info would be appreciated - thanks!

**Comment by ffleader1** [comment]
Make it 2023
Wonder why an obvious issue from 2015 still has not been fixed 8 years later.

**Comment by mklement0** [comment]
See also:

* https://github.com/PowerShell/PowerShell/issues/12129

**Comment by daxian-dbw** [comment]
@jazzdelightsme, given your knowledge and experience with the console on Windows, can you please take a look at this issue and see if you have any clues off the top of your mind? Thank you!

**Comment by jazzdelightsme** [comment]
@daxian-dbw I think I found it! I believe the problem is [here](https://github.com/PowerShell/PowerShell/blob/1f48d859d1877705bdfbabb6e3fc4ae8b43d3622/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2514C17-L2514C81), in `StartWithCreateProcess`, where we call `SetStartupInfo`:

```csharp
    SetStartupInfo(startinfo, ref lpStartupInfo, ref creationFlags);
```

That function fills in certain members of `lpStartupInfo`, notably `hStdInput`, `hStdOutput`, and `hStdError`. That *might* be the right thing to do for some other scenarios (I have no idea; this function could be used in different ways), but for the case when `_credential` is not null, I think it's definitely the wrong thing to do--it's what causes both consoles to be weirdly tied together. I feel pretty confident about that, because I set a breakpoint in `ADVAPI32!CreateProcessWithLogonCommonW` and then zeroed those three handles out in a debugger, and then things magically all worked fine in both consoles.

**Comment by daxian-dbw** [comment]
@jazzdelightsme Thank you for the investigation and pointing the direction! I will investigate further and see what the fix may look like.

**Comment by jamie-sandbox** [comment]
@daxian-dbw Any ETA on this fix?

@jazzdelightsme Do we know why removing `PSReadLine` resolves the issue when the bug is not actually in `PSReadLine`?

**Comment by jamie-sandbox** [comment]
## Workaround

For those hoping for a solution, it doesn't seem like one is coming any time soon.

As suggested by @JamesLear92, use `System.Diagnostics.Process` instead. It's not as complicated as it looks, the only downside is that it doesn't work in constrained language mode.

Note that the `Verb` and `WindowStyle` properties do not work when `UseShellExecute` is `$False`. The `CreateNoWindow` parameter _does_ work though.

If you need to use `Verb` and/or `WindowStyle`, just call an intermediary PowerShell instance with `-Command Start-Process powershell.exe -Verb RunAs -WindowStyle Maximized`. With this you get an elevated, maximised window running as whatever credentials you provided.

```
$Cred = Get-Credential
$Proc = New-Object -TypeName 'System.Diagnostics.Process'
$StartInfo = New-Object -TypeName 'System.Diagnostics.ProcessStartInfo'

$StartInfo.FileName = 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
$StartInfo.UseShellExecute = $False
$StartInfo.Arguments = '-NoLogo -Command C:\myscript.ps1'
$StartInfo.Domain = 'contoso'
$StartInfo.Username = 'bob'
$StartInfo.Password = $Cred.Password
$StartInfo.WorkingDirectory = 'C:\'

$Process.StartInfo = $StartInfo
$Process.Start() | Out-Null
```

**Comment by daxian-dbw** [comment]
Based on https://github.com/PowerShell/PSReadLine/issues/288#issuecomment-1673605171 (thanks @jazzdelightsme!), I opened https://github.com/PowerShell/PowerShell/pull/20853 to fix `Start-Process` in PowerShell.
I have verified on both Windows 11 and Windows 10 that both consoles work fine with the changes in that PR.

**Comment by daxian-dbw** [comment]
https://github.com/PowerShell/PowerShell/pull/20853 was merged, so close this issue as fixed.

**Comment by jamie-sandbox** [comment]
Praise the lord! Finally this is fixed!

Any word on when the fix will make its way to PowerShell 5.1 on Windows 10/11 and Server 2019/2022?

**Comment by mklement0** [comment]
@jamie-sandbox, given that it turned out to be problem in PowerShell, not PSReadLine, after all:

* My _guess_ is that the fix won't be backported to _Windows PowerShell_, given that the latter only receives security-critical fixes (but I'd be happy to learn otherwise).

* As of this writing, it's not clear (at least to me) in what PowerShell _Core_ version the fix will land - it doesn't have a "Backport"-label for v7.4.x at this point, and unless that changes, I think it will land only in v7.5.0

**Comment by jamie-sandbox** [comment]
@mklement0 Back to the workaround for now then... :disappointed:

**Comment by majkinetor** [comment]
Still not there in 7.5.1

**Comment by daxian-dbw** [comment]
@majkinetor the fix is in PowerShell 7.5.1. The reported `Start-Process powershell -Credential (Get-Credential) -PassThru` works fine with the fix (see the screenshot below).

![Image](https://github.com/user-attachments/assets/a92feb68-7dbd-4765-9d6d-c96d15512f9e)

**Comment by majkinetor** [comment]
Ty @daxian-dbw, I can confirm it works.

**Comment by PaulBendall** [comment]
In testing with PowerShell 7.5.1 I can confirm it works **IF** the Get-Credential username is in the _domain\user_ format; however if the username is in UPN format, _user@doman.com_ it fails with the same error as before the PR.

Possibly a known but unresolved issue with the handling of UPN in different versions of PowerShell and various cmdlet - [#12735](https://github.com/PowerShell/PowerShell/issues/12735)
