### ISSUE TITLE
When editing a command line with CJK glyphs under DBCS codepages, the command line will be displayed incorrectly

### ISSUE THREAD

**Issue by be5invis** [PowerShell/PSReadLine#289]
Steps of reproduction:
1. Change codepage to a DBCS one like `cp936`
2. Type `echo '一二三'`
3. Move the cursor to somewhere before `一二三`
4. Type anything. You will see the `一二三` disappeared.

I think maybe it is cuased by forgetting to move some of the character infos after the cursor...

**Comment by lzybkr** [comment]
The latest sources (for which I haven't published a release for) or the version installed in Win10 both have CJK support.

Maybe you're using 1.0.0.13?

**Comment by be5invis** [comment]
@lzybkr No, I'm using Windows 10's built-in PSReadline.
The console's main font has been set to a TTF font and the codepage is 936.

**Comment by lzybkr** [comment]
I believe this is fixed in #561.

I'll publish a pre-release version to the PowerShell Gallery as soon as they support pre-releases.

If you'd like to try a fix before that, you can build the lastest yourself from the master branch, or 
grab a build from AppVeyor like this [one](https://ci.appveyor.com/api/buildjobs/ust6h6k216i5gm81/artifacts/bin%2FRelease%2FPSReadline.zip).

Note the version number is now 2.0, so be sure to copy the contents to <your module dir>\PSReadLine\2.0.

**Comment by lzybkr** [comment]
I'll have an official prerelease build out next week if you want to verify this is fixed, otherwise you can grab a build out of appveyor [here](https://ci.appveyor.com/project/lzybkr/psreadline).
