### ISSUE TITLE
Add support for capitalizing, upcasing, and downcasing words

### ISSUE THREAD

**Issue by 3N4N** [PowerShell/PSReadLine#2912]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

In GNU Readline, I can use Emacs-like keys to capitalize, upcase, or lowercase the word after the cursor position. I can even change the keybindings. In my `.bashrc`, for example, I have:

```bash
# bind keys for case conversion
bind '"\ei": capitalize-word'    # default is alt-c
bind '"\eo": upcase-word'     # default is alt-u
bind '"\eu": downcase-word'  # default is alt-l
```

[Clink for Windows CMD](https://github.com/chrisant996/clink) has this feature.

### Proposed technical implementation details (optional)

I haven't looked into the PSReadline codebase yet. Strictly an user here. But I could look around out of curiosity if someone could point me to the code where stuff like `alt-del` or `alt-f/b` was implemented.

**Comment by lzybkr** [comment]
It's generally easy to find the source for specific key bindings - the name of the function in the source matches exactly what you see when you run `Get-PSReadLineKeyHandler`.

For the specific case of <kbd>Alt+f</kbd> the function is `ForwardWord`, but sometimes it is rebound with `ShellFowardWord` which defines a word as a PowerShell token instead of a simple word delimited by the characters in the option `WordDelimiters`.

It might be worth a brief discussion on whether or not it makes sense to add the "shell word" variants for these case changing functions. I initially thought yes, but maybe they wouldn't be useful at all as I don't think it would do what people expect, e.g. it would do nothing if the cursor is inside a string literal.

Vi mode does implement <kbd>~</kbd> - the function is named `InvertCase`, so you have some sample code to invert a single character.

**Comment by 3N4N** [comment]
About the shellword variants: I also don't think it'd be useful. But I don't use `ShellForwardWord` or other shellword variants either. So I may not be the best person to argue its usefulness.

And I wanted to try and see if I could add the support. Doesn't seem that difficult. Take the text from cursor position to where `ForwardWord` would move to and edit that text. But I don't understand how to import the module I just edited and built. There are build tutorials in the contribution guideline but no import tutorial. A default workflow scenario would help a lot the newcomers.

**Comment by lzybkr** [comment]
The easiest way to try out changes is in [MockPSConsole](https://github.com/PowerShell/PSReadLine/blob/master/MockPSConsole/Program.cs) which you can just build and run from this projects solution file.

Other ways a bit cumbersome because PowerShell loads PSReadLine by default.

**Comment by springcomp** [comment]
@3N4N I just published #2939 to outline and give you an idea how to quickly and effortlessly debug a custom build of PSReadLine on your own machine.

@lzybkr I hope you do not mind me hi-jacking the pull request infrastructure for this.

**Comment by lzybkr** [comment]
@springcomp - that's more involved than my approach, which was to:
* exit all instances of PowerShell
* launch an instance w/ `-noprofile -noninteractive` and in this instance:
  * backup the files I'm replacing in the PSReadLine module directory
  * copy over the files (usually just `PSReadLine.dll`)

This approach requires being an admin or installing a user local version of the module.

Alternatively, you could change the environment variable `PSModulePath` and avoid some of this, but I typically never did that because I knew I'd be using the version I built right away anyway.

**Comment by springcomp** [comment]
@lzybkr yes, your are right, it is a lot more involved.

However, it also means that the original instance of PSReadLine is always available and both can be run side by side.
I’m typically working on PSRL only occasionnaly and like to have a stable development environment otherwise.

Once the initial setup step hurdle is done, I find that I can quickly jump to working on a PSRL feature right away with a couple of keystrokes, without impacting other PowerShell sessions from the terminal or from Visual Studio code instances running.

I’m gonna go ahead an close my pull request and will try and work on drafting a wiki page detailing all three approaches:

– Using MockPSConsole.
– Using drop-in replacements of PSRL assemblies.
– Running a custom-built version of PSRL side-by-side.

Would that be helpful?

**Comment by 3N4N** [comment]
@lzybkr Sorry for being late. GH notifications must've been turned off back then.

I whipped something up yesterday. Opened a pull request. I'll move the conversation over there. Check that out when you have time. And thanks for the responses.
