### ISSUE TITLE
Bug open powershell

### ISSUE THREAD

**Issue by egg-jose** [PowerShell/PSReadLine#3001]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.19042
BufferWidth: 204
BufferHeight: 18

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/30965582/141112549-ddbf9aca-a63c-4902-9340-446a844739fe.png)


### Environment data

```console
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.19042
```

### Steps to reproduce

Open powershell

### Expected behavior

No errors

### Actual behavior

Has error

**Comment by iSazonov** [comment]
Please update to latest Beta4 version.

**Comment by egg-jose** [comment]
> Please update to latest Beta4 version.

How ?

**Comment by egg-jose** [comment]
Works for me

**Comment by daxian-dbw** [comment]
This issue was fixed in 2.2.0-beta3 version of PSReadLine. You can fix this by upgrading to the latest [2.2.0-beta4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.0-beta4). Instructions for doing so:
1. stop all instances of `pwsh`.
2. from `cmd.exe` run: `pwsh -noprofile -command "Install-Module PSReadLine -AllowPrerelease -Force"`

--------

If you want to remove that beta version of PSReadLine and use the 2.1.0 version of PSReadLine that's shipped with PowerShell 7.2, you can:
1. run `pwsh -noprofile -noninteractive` to start `pwsh` without loading PSReadLine
2. run `Uninstall-Module -Name PSReadLine -RequiredVersion <2.2.0-beta1 or 2.2.0-beta2> -AllowPrerelease` to remove the module. Or, you can manually remove that module folder.

**Comment by mazhar10** [comment]
I am not sure what daxian-dbw is stating - pwsh itself does not launch and causes the error I mentioned when I opened this issue. Also I am not sure why daxian-dbw is referencing a beta version of PSReadLine, my issue is with the release version of PowerShell 7.2.

**Comment by daxian-dbw** [comment]
@mazhar10 The environment data reported by the exception is:
```
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.19042
BufferWidth: 204
BufferHeight: 18
```
That indicates that you installed the `2.2.0-beta1` version of PSReadLine before. PowerShell 7.2 ships with the `2.1` stable version of PSReadLine, but since you have a `2.2.0-beta1` version installed in your module path, that higher version will be picked up when starting powershell. The `2.2.0-beta1` and `2.2.0-beta2` are incompatible to PowerShell 7.2 due to an intentional breaking change made in PowerShell 7.2, and that caused the error you observed.

So, the fix is to either update to `2.2.0-beta4` version of PSReadLine, or remove the existing `2.2.0-beta1/beta2` version of PSReadLine from your module path.

**Comment by mazhar10** [comment]
@daxian-dbw that is incorrect, you are reporting the Environment from someone else who polluted this issue of mine with something completely different running on a different OS :(
I opened the issue for a problem seen on Windows 11 with the release version of PowerShell 7.20. Others chimed in with *different* issues, and it is one of those there you see that environment data you reference. Please see my problem statement when this issue was opened.

**Comment by daxian-dbw** [comment]
I see. You should've point me to your issue. I didn't know you were referring to a different issue given that you are commenting in this issue.

The issue https://github.com/PowerShell/PowerShell/issues/16421 is not related to this PSReadLine issue, and @iSazonov must point you here by mistake.
Looking at that issue, it's a little messy there as someone else reported the `TypeLoadException` issue that is not related to your original issue ... I guess that's why @iSazonov referenced to this issue.

**Comment by mazhar10** [comment]
@daxian-dbw My sincere apologies, I am not sure how I even got notified about or involved with this bug! I had opened a different issue and assumed that I would receive notifications only about my bug. Sorry again daxian.

**Comment by daxian-dbw** [comment]
@mazhar10 No worries at all 😄
