### ISSUE TITLE
Trailing backslash is added when tab expanding folder paths

### ISSUE THREAD

**Issue by mikefrobbins** [PowerShell/PSReadLine#301]
When the PSReadLine module is imported, the behavior of tab expanding a path in the PowerShell console is changed to include a trailing backslash. This is different than the default behavior in both the ISE and the PowerShell console and could cause problems such as the one I've logged where script analyzer custom rules are ignored when the path contains a trailing backslash: https://github.com/PowerShell/PSScriptAnalyzer/issues/352

This behavior can be reproduced by tab expanding any path with a cmdlet such as Get-ChildItem while having PSReadLine imported and then removing the PSReadLine module to see the default behavior.

This was tested on Windows 10 Enterprise Edition with PowerShell version 5.0.10240.16384

**Comment by godeater** [comment]
Personally I find PSReadline's behaviour preferable in this case - having to manually type back slashes when you're tab completing a path is laborious and unnecessary.

**Comment by briantist** [comment]
I am used to the existing behavior of PowerShell that doesn't include the backslash, plus it's inconsistent with PowerShell ISE (where PSReadLine is not loaded).

It's especially unnatural when you want to reference a directory without a trailing slash, and have to press backspace (rather than tab completing and then pressing <kbd>\</kbd>).

So yeah I definitely vote for the old behavior, if only for consistency.

**Comment by lzybkr** [comment]
I'm reluctant to add an option for this behavior - I believe that an infinitely customizable experience leads to a poor experience because it can be too difficult to understand and configure the shell.

I'll leave the issue open though, elsewhere I've heard of at least one other request for this behavior, so I'm open to reconsidering given more feedback.

**Comment by godeater** [comment]
Wasn't the goal of PSReadLine to emulate GNU Readline? It seems counter
intuitive to me to then go back to the default powershell behaviour, if you
were trying to get away from that in the first place.

**Comment by lzybkr** [comment]
Well, there are Windows key bindings, so that isn't emulating GNU readline at all.

The goal is to provide a first class **PowerShell** command line editing experience that is familiar to anyone coming from the Windows world or the *nix world.

I recall making some choices that didn't directly emulate GNU if I thought there was a better PowerShell experience, but I don't recall specifics.

To be clear - if I thought GNU readline did something stupid, I wouldn't feel compelled to emulate it for compatibilities sake.  I might emulate it anyway, but I'd be comfortable with a better experience if I thought it was possible.

**Comment by lzybkr** [comment]
I forgot about issue #176 - I'm resolving this as a dupe so I don't have two issues that are basically the same thing.  The zsh solution is actually nice, and maybe it should just always work that way (in other words, it's not something you configure, it's just how it works.)
