### ISSUE TITLE
Should Vi mode really use its own internal clipboard?

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PSReadLine#319]
@srdubya : Thank you for implementing Vi mode!

I got tripped up trying to use "p" to paste some text from the system clipboard. I took a look at the code, and saw that Vi mode uses its own internal clipboard (just a string member called _clipboard).

I don't anticipate ever getting register support in PSReadLine (I don't think we want an entire vi implementation inside PSReadLine), so I think it would make sense to make the system clipboard the backing store for Vi mode's yank/put operations.

What do you all think?

**Comment by srdubya** [comment]
Hi Dan,  

I thought about implementing it that way but decided against it because:
  1)  Git Shell does not do this, at least on my system.
  2)  Lots of vi-mode commands put text into _clipboard.  I figured overwriting the system clipboard while editing a command would be viewed as an undesirable side effect most of the time.

I like it the way it is, but I'd support putting your idea behind a setting.

**Comment by gwojan** [comment]
@jazzdelightsme, @srdubya Interesting! I was just going to request that this be configurable. :smile: I too would like access to the system clipboard because I'm constantly doing the copy/paste thing from other sources into the PowerShell prompt. I always use the unnamed register in gVim/VsVim.

With that said, I really like the the existing visual copy capability from @lzybkr. That's why I originally asked that `v` be changed to allow visual selection and `V` actually launch `$env:VISUAL`.

**Comment by lzybkr** [comment]
Agreed, a configuration option is a good idea.  I use that setting in Vim and find it extremely useful, but it's not for everybody.

As for registers - I could see adding them.  Emacs mode has the kill ring which is similar to having multiple registers.

**Comment by jazzdelightsme** [comment]
Thank you everyone for the discussion!

@srdubya : I personally don't care much what git bash does :), but item 2 alone is a good enough reason on its own to tread carefully, like putting it behind an option. When I get a chance I'll think about how registers might be implemented, unless somebody beats me to it.

**Comment by springcomp** [comment]
My work on #333 currently awaiting review as PR #811 lead me to implement the internal clipboard as a register. It could then be extended for _named_ registers fairly easily.

**Comment by wang-jinbo** [comment]
So if I want to vi mode use system clipboard instead of its own, what should I do for it?

**Comment by springcomp** [comment]
@Wongboo  Make vi-mode use the system clipboard is not currently supported, unfortunately.

Not sure this would be worth it to be honest.

One way would be to have an option, which would replace the internal clipboard and use the system clipboard.

A better way would be to support the `+` register which is the standard way in vim to use the system clipboard. Thus, the user would have to type sequences like: <kbd>"</kbd><kbd>+</kbd><kbd>y</kbd><kbd>y</kbd> or <kbd>"</kbd><kbd>+</kbd><kbd>p</kbd> for instance.

Again, I’m not really sure there is a use case for it, though 🤔.

**Comment by daxian-dbw** [comment]
> A better way would be to support the `+` register which is the standard way in vim to use the system clipboard. Thus, the user would have to type sequences like: <kbd>"</kbd><kbd>+</kbd><kbd>y</kbd><kbd>y</kbd> or <kbd>"</kbd><kbd>+</kbd><kbd>p</kbd> for instance.

I agree that would be the better way to go, if we really decide to support it.
Given that there is no plan to support the system clipboard as a configuration and that the discussion has made it clear that using an internal clipboard is the desired design, I will close this issue.
