### ISSUE TITLE
Slow Powershell startup due to PSReadLine

### ISSUE THREAD

**Issue by gerardog** [PowerShell/PSReadLine#3192]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

Hi! This was reported as #2143, but somehow marked as a question instead of a bug, then closed.

When using my Android phone as a wifi hotspot, W11, Powershell Core (7.2.1) with PSReadLine 2.1.0 takes 15 seconds to start.

I disabled all PS telemetry as shown [here](https://github.com/PowerShell/PowerShell/issues/16234#issuecomment-944249264), rebooted, but the problem still persists. The problem goes away when running `pwsh -NonInteractive` and can be then reproduced (15 seconds delay) at 'Import-Module PSReadLine'

```
C:\>pwsh
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.
<!-- 15 seconds delay! -->

PS C:\> exit

C:\>pwsh -noninteractive
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

<!-- fast! no delay ! -->

PS C:\> Measure-Command {Import-Module PSReadLine}
(...)
TotalSeconds      : 15.0726826
```

During this wait, TCPView shows

![image](https://user-images.githubusercontent.com/3901474/151687752-48288f88-ddea-42df-8cff-64917df385d4.png)

`ipconfig /displaydns` shows a lot of stuff but certaintly `ctldl.windowsupdate.com` and `fg.download.windowsupdate.com.c.footprint.net` rings a bell (same IP). 

```
PS C:\Users\gerar> ipconfig /displaydns
(...)

    ctldl.windowsupdate.com
    ----------------------------------------
    Record Name . . . . . : ctldl.windowsupdate.com
    Record Type . . . . . : 5
    Time To Live  . . . . : 41
    Data Length . . . . . : 8
    Section . . . . . . . : Answer
    CNAME Record  . . . . : wu-shim.trafficmanager.net

    Record Name . . . . . : wu-shim.trafficmanager.net
    Record Type . . . . . : 5
    Time To Live  . . . . : 41
    Data Length . . . . . : 8
    Section . . . . . . . : Answer
    CNAME Record  . . . . : fg.download.windowsupdate.com.c.footprint.net

    Record Name . . . . . : fg.download.windowsupdate.com.c.footprint.net
    Record Type . . . . . : 1
    Time To Live  . . . . : 41
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 200.32.103.248

```

It is possible that my ISP is doing something bad, but the point here is that PSReadline shouldnt be taking so long to start anyway. If this an auto-update feature, can be disabled? can occur in background?

Thanks!

### Environment data

```console
PS Version: 7.2.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 133
BufferHeight: 32
```

### Steps to reproduce

Use a terrible ISP. An Android hotspot may help. Open Pwsh and then see how it takes 15 seconds to show a PS prompt.

### Expected behavior

Fast start time

### Actual behavior

`Import-Module PSReadLine` takes 15 seconds.

**Comment by gerardog** [comment]
Oh... this may be a problem with PSReadline code signing certificate revocation check, as explained in [Signed PowerShell cmdlets run slower than unsigned cmdlets](https://support.microsoft.com/en-us/help/4523292/signed-powershell-cmdlets-run-slower-than-unsigned-cmdlets)  [`[alternate link]`](https://mskb.pkisolutions.com/kb/4523292).

**Comment by daxian-dbw** [comment]
@gerardog This is due to a security check in PowerShell on signatures of script module as well as DLL files. See the original issue: https://github.com/PowerShell/PowerShell/issues/10983.
Here are some comments from that issue that may be of interest to you:
https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-552023412
https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-552143899
https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-552667564
https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-553609273

The conclusion was "by design + needs workaround for air gapped scenario", and @TravisEz13 [pointed to this article](https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-551976417) as the solution for the OP: https://docs.microsoft.com/en-us/archive/blogs/winsdk/reducing-the-time-to-perform-a-crl-check-on-isolated-networks.

For your case, it looks like the Android hotspot may likely be the cause of the slow certificate revocation list processing (CRL checking).

**Comment by gerardog** [comment]
Indeed. Thanks @daxian-dbw. Not sure why that conversation didnt called my attention while googling at the issue. Hope this issue helps someone else spend less time investigating the problem.
