### ISSUE TITLE
Add config option to disable completion of Parameter Aliases

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PSReadLine#3198]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

In https://github.com/PowerShell/PowerShell/issues/16658 specifically https://github.com/PowerShell/PowerShell/issues/16658#issuecomment-1001809209 it was raised that parameter aliases can cause a less than optimal completion experience for end users.

Therefore I believe that this should be configurable as to allow a more customised experience.

### Proposed technical implementation details (optional)

A configuration option that allows the user to control whether or not to surface parameter aliases as part of completion options, optionally showing them in brackets after the parameter completion value.

**Comment by daxian-dbw** [comment]
@kilasuit I believe that would need to be an ask to PowerShell tab completion, instead of PSReadLine, because PSReadLine doesn't know which one is a parameter alias.
```
PS:11> $s = TabExpansion2 -inputScript 'Start-Sleep -m' -cursorColumn 'Start-Sleep -m'.Length
PS:12> $s.CompletionMatches

CompletionText ListItemText    ResultType ToolTip
-------------- ------------    ---------- -------
-Milliseconds  Milliseconds ParameterName [int] Milliseconds
-ms            ms           ParameterName [int] ms
```

Also, I'm not sure we should have such a configuration. It likely won't be discoverable, and the default behavior will be showing everything as today, and I think most user will just depend on that.
