### ISSUE TITLE
VS Code Powershell Terminal bug

### ISSUE THREAD

**Issue by adityaroshandash** [PowerShell/PSReadLine#3210]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![Screenshot 2022-02-03 134845](https://user-images.githubusercontent.com/99230514/153702584-0bbc4d9f-2f10-453e-b76f-a78a88d4e96d.jpg)

### Environment data

```console
N/A
```

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by daxian-dbw** [comment]
You were using a very old version of PSReadLine (2.0.0-beta2 or prior). This issue was already fixed (see #1306). Please upgrade to the [2.2.1-rc1 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.1-rc1) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
