### ISSUE TITLE
Unify capitalization behavior of `AcceptNextSuggestionWord`, `NextHistory`, and `PreviousHistory` to behave like the built-in `TabCompleteNext` and `MenuComplete`.

### ISSUE THREAD

**Issue by blakeNaccarato** [PowerShell/PSReadLine#3263]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

Standard "tab completion", bound to `Tab` by default, executes the command `TabCompleteNext`. This chooses the next valid completion from `MenuComplete`, and also applies proper capitalization to user input. For example, inputting `get-c_` and tabbing through eventually yields `Get-ChildItem`. Proper capitalization is also applied to input when doing `MenuComplete`, and arrowing through the options also applies proper capitalization to the completion text.

With the newer Predictive IntelliSense feature in PSReadLine 2.1+, when `PredictionViewStyle` is set to `ListView`, a menu similar to `MenuComplete` can be used to complete user input, except informed by history and an optional plugin instead of possible cmdlets. For completions from the "history" source, it completes the command with whatever capitalization the user happened to have used when they last executed that command. The same goes for `AcceptNextSuggestionWord`.

It would be nice if, when the user types `get_ch_` and they have a command in their history that looks like `GeT-ChiLdItEm my\special\path` (an egregious example, I know), the new completion features would automatically normalize the case of known cmdlets, resulting in `Get-ChildItem my\special\path`.

This unification of behavior would involve modifying `AcceptNextSuggestionWord`, `NextHistory`, and `PreviousHistory`.

**Comment by StevenBucher98** [comment]
The source of the predictors come from history and so we can't for certain know what is suppose to capitalized or not because we don't know the source of truth from history. Validating if you are in the right capitalization would likely be performance hit if we did it every time before accepting suggestions. 

We likely wont be able to implement this until we make more improvements to the history predictor in general. Potentially may be interesting to add source of truth or command discovery information to a more advanced history details

**Comment by blakeNaccarato** [comment]
I see, thank you for your reasoning! I will close it as not planned, for now, then.
