### ISSUE TITLE
Pasting creation of non-custom objects from hashtable

### ISSUE THREAD

**Issue by peombwa** [PowerShell/PSReadLine#3306]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot
Inspect the pasted snippet. You'll notice that `Conditions` is being prefixed to the `DisplayName` property.
![image](https://user-images.githubusercontent.com/7061532/167702318-09e84927-2dac-4f5b-94e2-9623ee764786.png)

### Environment data

```console
PS Version: 7.2.3
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.5
PSReadLine EditMode: Windows
OS: 10.0.22598.1 (WinBuild.160101.0800)
BufferWidth: 286
BufferHeight: 70
```

### Steps to reproduce

1. Install and import module:
``` powershell
Install-Module Microsoft.Graph.Identity.SignIns
Import-Module Microsoft.Graph.Identity.SignIns

```
2. Copy and paste the following to a new PowerShell session:
``` powershell
$params = [Microsoft.Graph.PowerShell.Models.IMicrosoftGraphConditionalAccessPolicy]@{
	DisplayName = "Access to EXO requires MFA"
	State = "enabled"
	# Add more properties.
}
```
3. Inspect the pasted snippet. You'll notice that `Conditions` is being prefixed to the `DisplayName` property.
![image](https://user-images.githubusercontent.com/7061532/167702318-09e84927-2dac-4f5b-94e2-9623ee764786.png)

### Expected behavior

The pasted snippet should match the copied one i.e.,
``` powershell
$params = [Microsoft.Graph.PowerShell.Models.IMicrosoftGraphConditionalAccessPolicy]@{
	DisplayName = "Access to EXO requires MFA"
	State = "enabled"
	# Add more properties.
}
```

### Actual behavior

`Conditions` is being prefixed to the `DisplayName` property.
![image](https://user-images.githubusercontent.com/7061532/167702318-09e84927-2dac-4f5b-94e2-9623ee764786.png)

**Comment by jspern** [comment]
@peombwa I'm unable to repro this in my environment -- same version of PS and PSReadLine that you are using.

![image](https://user-images.githubusercontent.com/41965203/167706594-9f7ade86-aa2d-4aa2-a65f-37b64553c836.png)

**Comment by daxian-dbw** [comment]
The issue reproduces when you paste using Right Click instead of <kbd>Ctrl+v</kbd>.
The "spaces" before `DisplayName =` is actually <kbd>Tab</kbd>. When using Right Click, the terminal sends the text character by character, and it's the same as an interactive user typing those characters from the console application's perspective, and thus the <kbd>Tab</kbd> will trigger a tab-completion, and the tab-completion result is `Conditions`. That's why it looks like `Conditions` gets prepended from nowhere.

Technically, this is the by-design behavior, but we want to fix the Right Click behavior in general and that is tracked by #579.
