### ISSUE TITLE
PsReadline doesn't save my command script automatically.

### ISSUE THREAD

**Issue by delaviux** [PowerShell/PSReadLine#3573]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.3.2
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.22621.1265 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

Enter the following script in Powershell:
 
(netsh wlan show profiles) | Select-String "\:(.+)$" | %{$name=$_.Matches.Groups[1].Value.Trim(); $_} | %{(netsh wlan show profile name="$name" key=clear)}  | Select-String "Key Content\W+\:(.+)$" | %{$pass=$_.Matches.Groups[1].Value.Trim(); $_} | %{[PSCustomObject]@{ PROFILE_NAME=$name;PASSWORD=$pass }} | Format-Table -AutoSize 

### Expected behavior

PSReadline should automatically save my script to the file ConsoleHost_History.txt.

### Actual behavior

My script is not saved.

**Comment by StevenBucher98** [comment]
Thanks for the issue @lmgr1992! I believe this is by design as we try our best to not save potentially sensitive data in history, so anything containing strings like `password` are not included, you can read more about this here, https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-7.3#command-history
