### ISSUE TITLE
Close console with Ctrl-D

### ISSUE THREAD

**Issue by beruic** [PowerShell/PSReadLine#358]
I can't figure out how to configure this. Is it even possible?

**Comment by srdubya** [comment]
Switch to vi-mode, it's in there by default.

**Comment by lzybkr** [comment]
In emacs mode, it is also the default, but you can bind it yourself with:

Set-PSReadlineKeyHandler -Key Ctrl+d -Function DeleteCharOrExit

**Comment by beruic** [comment]
@srdubya How do I change to Vi-mode. It complains no matter what I try to give it.

**Comment by beruic** [comment]
@srdubya Do you by any chance have a good ps1-file?

**Comment by srdubya** [comment]
Here's what I use.  Format-Bash is a module I created to sort items column wise.  PS may already provide a way of doing this, but since I didn't/don't know about it I wrote my own.  I'd be happy to share it if you're interested.

function prompt {
    Write-Host( [Environment]::NewLine + $(get-location) )
    return "> "
}

if( $host.Name -eq 'ConsoleHost' ) {
    Import-Module PSReadline
    <##>
    Set-PSReadlineOption -EditMode Vi
    Set-PSReadlineOption -DingTone 2400
    Set-PSReadlineOption -DingDuration 30
    Set-PSReadlineOption -ViModeIndicator Prompt
    Set-PSReadlineOption -ExtraPromptLineCount 1
    Import-Module Format-Bash
    <##>
}

Function lsf($dir) {
   Get-ChildItem $dir | Format-Bash
}
Function lsa {
   Get-ChildItem -Hidden | Format-Bash -All
}
Function ll {
   Get-ChildItem -verbose
}

Function which($name) {
    Get-Command $name | Select-Object -ExpandProperty Definition
}
Function whence($name) {
     Get-Command -Syntax $name
}

$VIMPATH    = "C:\Program Files (x86)\Vim\vim74\vim.exe"
Set-Alias vi $VIMPATH
Function Edit-Profile
{
    vi $profile
}
Function Edit-Vimrc {
    vi $home_vimrc
}
$env:VISUAL = "vi"

$env:PATH = $env:Path + ";C:\Program Files\Git\bin"

**Comment by beruic** [comment]
Well, my main issue with this is that `Set-PSReadlineOption -EditMode Vi` is not accepted. I get:

```
Set-PSReadlineOption : Cannot bind parameter 'EditMode'. Cannot convert value "Vi" to type "Microsoft.PowerShell.EditMo
de". Error: "Unable to match the identifier name Vi to a valid enumerator name. Specify one of the following enumerator
 names and try again:
Windows, Emacs"
At C:\Users\jimmy\Documents\WindowsPowerShell\profile.ps1:9 char:32
+ Set-PSReadLineOption -EditMode Vi
+                                ~~
    + CategoryInfo          : InvalidArgument: (:) [Set-PSReadlineOption], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.SetPSReadlineOption
```

**Comment by beruic** [comment]
I solved it now. It seems that the Vi-mode is not in the default Windows 10 version of PSReadline. This makes it necessary to to a

``` powershell
PS> Install-Module -Name PSReadline
```

contrary to what the documentation says.
I also put

``` powershell
Import-Module PSReadLine -MinimumVersion 1.2
```

in my ps1, since it seems to prefer version 1.1.
