### ISSUE TITLE
Deleting a word while MenuComplete is active leaves the selected word in the buffer

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PSReadLine#3598]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.4.0-preview.1
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 282
BufferHeight: 9001
```

### Steps to reproduce

1. Type in `Get-C`
2. Press Ctrl+Space to trigger menu complete.
3. Press Ctrl+Backspace to delete a word
4. The line will now say `Get-ertificate`

### Expected behavior

The menu is cleanly closed and the word is deleted so the line should say `Get-`

### Actual behavior

The menu is closed, the word is deleted and whatever was remaining from the word is appended to the line, so it says: `Get-ertificate`

**Comment by StevenBucher98** [comment]
Thanks for the issue @MartinGC94! Able to repro and marked as a bug

**Comment by daxian-dbw** [comment]
I think this is a by-design behavior. The menu completion handles some keys by itself, but for those it doesn't handle, it
1. assumes the current highlighted completion text is accepted, _and_
2. cursor position unchanged, right at the first character of the highlighted completion text, _and_
3. clear the menu, _and_
4. apply the real action registered for that key.

That's why you get `Get-ertificate` from the repro steps above -- because the cursor position is at index 5.
This behavior also provides you the following results when replacing the 3rd step with other key bindings:

- Pressing `Ctrl+a` gives you `Get-Certificate` being highlighted as selected
- Pressing `Ctrl+RightArrow` or `End` gives you `Get-Certificate`
- Pressing `Ctrl+Enter` insert a line above `Get-Certificate`
- Pressing `Ctrl+Shift+RigthArrow` gives you `Get-Certificate` with the `ertificate` part highlighted.
- etc.

Changing the current behavior will be a breaking change.

**Comment by MartinGC94** [comment]
@daxian-dbw That explanation makes sense but I can't say I agree with that design.  
I look at the MenuComplete function like an IntelliSense menu where you actively have to accept/decline the suggestion, and the only reason the text shows up inline the way it does is because it's a console interface where pop up menus aren't really possible. From that perspective the current behavior where it assumes whatever is highlighted should be accepted doesn't make much sense but maybe I'm alone with that perspective.
