### ISSUE TITLE
How to read highlighted text from the output not the command line?

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PSReadLine#361]
I see how you can read highlighted text on the command line.

Is there a way to read highlighted text outputted from a previous command?

I’d like a short cut key where I highlight the url, `ctrl+shift+b`, and it launches it in the browser.

![image](https://cloud.githubusercontent.com/assets/67258/13920954/f858e57e-ef4b-11e5-805d-67bab970e0e3.png)

**Comment by lzybkr** [comment]
There is a win32 api GetConsoleSelectionInfo. PSReadline doesn't have a p/invoke signature for it, so you'll need some C#/Add-Type to use it, but it is possible. I don't plan on adding anything to PSReadlne though, because it will be confusing as I already have GetSelectionState which is different from the console's idea of what is selected.

**Comment by dfinke** [comment]
Gave this a try. I have no clue. Could you provide an example to extend?
