### ISSUE TITLE
F7 history window: set focus to filter line

### ISSUE THREAD

**Issue by eugenesvk** [PowerShell/PSReadLine#363]
You have a great shortcut to view command history on `F7` that shows said history in a GUI window. However, on launch you can't just start typing a command since filter line doesn't have focus.
Is there a way to make it focused so I don't have to do an extra click?
Thanks

Windows 10.0.10586.0 PowerShell 5.0

**Comment by gwojan** [comment]
To avoid clicking pressing `Ctrl+E` will set focus in the filter field.

**Comment by lzybkr** [comment]
I don't know - maybe @daviwil knows some magic to get Out-GridView to set the focus - probably requires some reflection if you want to avoid a mouse click/key press though.

**Comment by eugenesvk** [comment]
@gwojan thanks for the tip! That's already better than using a mouse. Hopefully @daviwil would do his magic and make it autofocus to avoid even that.

**Comment by daviwil** [comment]
There doesn't appear to be a parameter for this and I don't think there will be an easy way to make it happen via reflection or some other hacky means.

Seems like it would be useful to have a `-Focus` param that can take a value of `List` or `Filter` so that the caller can decide which bit of UI gets focused when the window appears.  I'll see about getting this added in a future version of PowerShell.

**Comment by lzybkr** [comment]
Closing as this is more of a request on `Out-GridView` which might not ever happen.
