### ISSUE TITLE
How to browse arguments / parameters while typing automatically based on --help ?

### ISSUE THREAD

**Issue by oxysoft** [PowerShell/PSReadLine#3848]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

Hi, I'm not sure if I'm missing something, this seems like the most basic use-case. The --help pages are all written already in a standard format for each command, so I'm not sure why it's not fetching the information and displaying it as soon as I type two dashes. Is there a way to achieve this behavior with PSReadLine? I'm hoping there's a list somewhere with all such cool plugins that people have made for PSReadLine?

Thanks

**Comment by daxian-dbw** [comment]
@oxysoft Please take a look at https://github.com/PowerShell/completionPredictor, which may offer what you want. That module is available on PowerShell Gallery.

For more information about the predictive intellisense, see https://learn.microsoft.com/powershell/scripting/learn/shell/using-predictors?view=powershell-7.3

**Comment by oxysoft** [comment]
Hi, I see now that it was working all along, the problem is that it doesn't work with RipGrep. Is it because the argument format is different than typical PowerShell? (unix style with `-L` or `--long-name`) To be clear I am using the Windows binary for ripgrep, however the usage is not adapted to PowerShell's philosophy.

**Comment by daxian-dbw** [comment]
The `CompletionPredictor` depends on tab completion in PowerShell as the source for prediction. It requires the completion to be enabled for a command (`RipGrep` in this case) and the completion needs to be fast enough (timeout is 20ms as of today).

In theory, you can create the tab completion for `RipGrep` (see [Register-ArgumentCompleter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.3)), but you will need to do completion based on the help docs for that tool instead of depending on spinning up `RipGrep`, because the overhead of starting a process is too much for the timeout we have for prediction.
