### ISSUE TITLE
ctrl+v unexpected behavior

### ISSUE THREAD

**Issue by Gopinath-Dehury** [PowerShell/PSReadLine#3861]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
unexpected behavior
```

### Screenshot

![Screenshot 2023-11-10 201142](https://github.com/PowerShell/PSReadLine/assets/129596617/b964c967-ab15-4470-827f-698ed8ebe145)
![Screenshot 2023-11-10 201248](https://github.com/PowerShell/PSReadLine/assets/129596617/f997f266-6ebe-47a3-a3b8-1da2578855fb)

### Environment data

```console
Avg ghvhjv hbhbvh
```

### Steps to reproduce

ctrl +v in the terminal and show those screenshot view 

### Expected behavior

should paste my copied text on the terminal

### Actual behavior

should paste my copied text on the terminal but show unexpected things that I can't understand

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.3.4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.4) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
