### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by Marc3le** [PowerShell/PSReadLine#3950]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![Screenshot 2024-02-18 111112](https://github.com/PowerShell/PSReadLine/assets/152316434/ce63bba6-ccdc-4ab0-ba33-f2c437f7b433)
![Screenshot 2024-02-18 111137](https://github.com/PowerShell/PSReadLine/assets/152316434/b903db77-8f1f-46cd-b9fb-9d98daa48a2f)

### Environment data

```console
I don't know :(
```

### Steps to reproduce

Compiling the code

### Expected behavior

GIving me the output

### Actual behavior

Giving me the data shown in the screenshot

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.3.4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.4) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
