### ISSUE TITLE
Search history forward: The cmd way

### ISSUE THREAD

**Issue by monoblaine** [PowerShell/PSReadLine#429]
When I install PSReadLine, a console feature regarding the "command history traversal" that I use the most gets broken. That is:
1. Launch a PowerShell instance, type `ls` and press `Enter`.
2. Now type `cls` and press `Enter`.
3. Press `up arrow` 2 times. (You should get `ls`)
4. Press `Enter`.
5. Press `down arrow`. (You should get `cls` now. You get nothing if PSReadLine module is installed.)

This history search behavior is sort of stateful: If you've executed a command from your history, and do a "History Forward" action after that, you should get the next command in history that comes after that.

The functions `HistorySearchForward` and `HistorySearchBackward` is only a part of what I need. Pressing the down arrow **in a blank new line** should do a `HistorySearchForward` **starting from the last executed command (if any)**.

Actually it sounds to me like "OMG HOW COME NOBODY EVER REALIZED THIS BEFORE?" And I know that possibly cannot be true. So I hope I'm not pointlessly mentioning some "THAT'S A FEATURE" case.

(By the way, I love the syntax coloring. That's why I seek a solution that doesn't include uninstalling the module.)

**Comment by lzybkr** [comment]
I'm well aware of the behavior you describe, it was an intentional design decsion to mimic bash instead of cmd as the cmd behavior is typically quite confusing when you're not quite sure where you are in history.

In Emacs mode, `Ctrl+o` is bound to `AcceptAndGetNext`, which is very nearly what you want. I suggest trying it, e.g. `Set-PSReadlineKeyHandler -Key Ctrl+o -Function AcceptAndGetNext` and then, instead of `Enter` then `DownArrow`, you instead just use `Ctrl+o`. You may find you prefer this - it's one less key, and you can still use `DownArrow` if you want something other than the immediate next command line.

**Comment by monoblaine** [comment]
Last night I tried using `AcceptAndGetNext` and felt like a newbie trying to exit Vim :D But thanks for the suggestion anyway!
