### ISSUE TITLE
What is macOS Command key?

### ISSUE THREAD

**Issue by vors** [PowerShell/PSReadLine#457]
I'm trying to do some custom binding for macOS. Mac has a `Command` key which similar to `Win` key in some senses. I.e. bootcamp dual-boot treats it as `Win` key when you run Windows on Apple hardware. What's the right way to use it in PSReadLine? I was reading Key.cs, but could not make sense out of it.

**Comment by lzybkr** [comment]
Maybe you figured it out already, but I don't think the `Command` key is usable in PSReadLine.

PSReadLine only supports `Alt` (`Option` on a Mac), `Control`, and `Shift` modifiers. PSReadLine does not support bindings using the `Windows` key, so it makes sense that it wouldn't support `Command` either.

**Comment by vors** [comment]
Yes, `Windows` == `Command`

> does not support bindings using the Windows key

Why?

**Comment by lzybkr** [comment]
Because it's not implemented.

`Console.ReadKey` returns immediately when `Windows` is pressed, so any custom binding would need to be a chord, like `LeftWindows,k` instead of `LeftWindows+k`.

But as a chord, the `Windows` key brings up the start menu, so you really need the modified form, and .Net just doesn't support that.

**Comment by lzybkr** [comment]
I should add - it wouldn't be portable anyway - I'm not seeing the `Windows` key in Linux, tested on CentOS via `showkey -a` - no .Net involved at all.
