### ISSUE TITLE
Is it possible to reload history from file?

### ISSUE THREAD

**Issue by aronser** [PowerShell/PSReadLine#494]
Sorry if the question is trivial, and I just inattentively read the documentation.

Command history is loaded on module import from a default file.
If you change the file with command "Set-PSReadlineOption -HistorySavePath" new commands are written to it, but the old commands remains the same from the module import time.
Is there a way to reload command history from a file?

**Comment by gwojan** [comment]
Can't you simply copy the old file to the new location?

**Comment by aronser** [comment]
No, it's not the case.

I set history file in Microsoft.PowerShell_profile.ps1 by session context (several files).
Commands that I execute correctly writing to the file I set by profile.
But when I start a new session with the same context command history is loaded from a default file ConsoleHost_history.txt, while new commands will still be written to the file I set.

**Comment by lzybkr** [comment]
It's possible, but a little tricky.  You could call `[Microsoft.PowerShell.PSConsoleReadLine]::ClearHistory()` followed by a bunch of calls to `[Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory()` - the tricky part is reading the history file.

Typically each line in the history file is a complete command, but multi-line commands use a backtick, so there is some extra processing needed beyond:

```powershell
Get-Content $newHistoryFile | % { [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($_) }
```

It's not much processing though, it might still be a one-liner, more or less, just a tricky one liner.

**Comment by aronser** [comment]
that's nice, thank you very much!

**Comment by UberKluger** [comment]
@lzybkr How about

(Get-Content -raw $newHistoryFile) -split "[^\`\`\`r]\`r?\`n" | % { [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($_) }

Lines are split on \n or \r\n but not if there is an immediately preceding \`.
For those wondering about [^\`\`\`r], this is so \`\r\n doesn't match. [^\`]\`r?\`n would match the \r\n part as something that isn't a back-tick followed by empty followed by \n.

The other "tricky" part is that calling AddToHistory appends the command string to the history file, so you need to have HistorySavePath set to a disposable file if you don't want your saved history corrupted (or worse, create a potential infinite loop as the added history gets read back in and added to history again).

**Comment by LispEngineer** [comment]
I'm trying these two suggestions from @UberKluger  and @lzybkr but unfortunately, on PowerShell Core 7.1 they do not seem to be working for me. I get a long list of errors for each line in the history.

To work around the "adding history to history" problem, I did this though:

```posh
$histPath = (Get-PSReadLineOption).HistorySavePath
# Turn off our history saving temporarily so we can load it without duplication
Set-PSReadLineOption -HistorySavePath 'C:\\NUL'
# LOAD HISTORY HERE (cannot get it working)
Set-PSReadLineOption -HistorySavePath $histPath
```

The errors I get are:
```
MethodInvocationException: D:\...\profile.ps1:59
Line |
  59 |  … ch-Object { [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($_ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "AddToHistory" with "1" argument(s): "Object reference not set
     | to an instance of an object."
```

The `AddToHistory` works fine from the PS prompt, including adding to local history and the history file.

I should also note that turning off history with `SaveNothing` will only delay the newly added history to be added to the history file when you restore it to `SaveIncrementally`.

**Comment by hrxn** [comment]
FWIW, apparently `[Microsoft.PowerShell.PSConsoleReadLine]::ClearHistory()` does only clear the history that is present in the current session.

When I start a new terminal and do `Get-Content (Get-PSReadLineOption).HistorySavePath` I still see the entire saved history.
So the PSReadLine history file is unaffected by this. I guess this is intentional?

To really get rid of the entire history, 

`Remove-Item (Get-PSReadlineOption).HistorySavePath`
*or*
`Clear-Content (Get-PSReadlineOption).HistorySavePath`

seems to work for me..

**Comment by left1000** [comment]
So, 

Get-Content $newHistoryFile | % { [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($_) }

is close to something that would work for me, but I've saved my history of commands as an xml file, and the above loads all the xml formatting instead of just the commands.

Why am I using an xml file? because I was trying to use Get-History with Add-History which do add saved history of commands to a history, it's just not compatible with PSReadline.

I can even Add-History then save the history in plaintext, without the xml formatting, but the problem is that this type of powershell history is still each line:

id duration command

is there anyway to load powershell history data as PSReadline history data without having to manually massage the syntax to eliminate extra information like the command id or the command time?

edit: I've realized I need to just give each powershell tab it's own profile and set each profile to load a different psreadline history save location on load. as of yet though I don't know the powershell profile commands specifically to set the history save location, because isn't the save location for the profile something that has to already exist before the profile is read?

**Comment by left1000** [comment]
Nevermind it was very easy and I got it working, sorry to reply to myself.

I just setup windows terminal to launch powershell with this flag setup:

C:\PowerShell7\7\pwsh.exe  -noexit -noprofile -f "profileforTAB1.ps1"

and the contents of the profile were merely

Set-PSReadLineOption -HistorySavePath "TAB1.PSReadlineHISTORY.txt"

this then can be repeated for however many isolated tabs of powershell you want in windows terminal and you can be sure that the psreadline command history's never cross-pollenate.

While I'm at it I found the easiest way to export powershell session history data and convert it into psreadline history data. 

run 

Get-History | Export-Csv History.csv

open History.csv in a spreadsheet software program, then just copy column B then paste it into a writer software program and save as txt and override the fact some formatting data may be lost (psreadline command history save files don't have extra data like id# or duration or formatting)


Using these convoluted steps allows you to manipulate powershell session history save data and psreadline history data and to both load it and save it. The tricky part though here is that the easiest way to load psreadline history data is to simply start over again using a history save file that's already been made perfect by you before you begin (but while this sounds silly it was actually quite easy when I just did it.)

**Comment by nymation** [comment]
> It's possible, but a little tricky. You could call `[Microsoft.PowerShell.PSConsoleReadLine]::ClearHistory()` followed by a bunch of calls to `[Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory()` - the tricky part is reading the history file.
> 
> Typically each line in the history file is a complete command, but multi-line commands use a backtick, so there is some extra processing needed beyond:
> 
> ```powershell
> Get-Content $newHistoryFile | % { [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($_) }
> ```
> 
> It's not much processing though, it might still be a one-liner, more or less, just a tricky one liner.

Wow. I'm new to powershell, but I didn't expect a simple one-liner to actually work. I've been at it for days lol. You solved my problem, so you have my gratitude.

**Comment by God-damnit-all** [comment]
So, I've noticed that if `Set-PSReadlineOption -HistorySaveStyle SaveNothing` is part of the initial set of startup commands, no history will be loaded.

I attempted to get around this issue through including this in the startup commands:

```powershell
&{
  $ln = (Get-Content (Get-PSReadlineOption).HistorySavePath -Raw) -split '(?<![`\r])\r?\n'
  for( $i=0; $i -lt $_.Count-1; $i++ ){  # -1 to exclude last line (empty)
    [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($ln[$i])
  }
}
```

However, I get the error `Exception calling "AddToHistory" with "1" argument(s): "Object reference not set to an instance of an object."` – which I guess means that PSReadLine's history can't be interacted with until after the startup commands complete because of the way the module loads up.

Another thing I tried is to invoke the `PSConsoleHostReadLine` function during startup, which does work ... sort of. For some reason it makes the first input line blank until I hit enter, and then there's a brief pause:

![](https://github.com/PowerShell/PSReadLine/assets/53661808/efde92ca-c8ec-4871-8e8f-3aefbbdde2cb)

Any recommendations?

**Comment by hrxn** [comment]
> So, I've noticed that if Set-PSReadlineOption -HistorySaveStyle SaveNothing is part of the initial set of startup commands, no history will be loaded.

You mean if you use that in your $PROFILE?

If that's what you meant.
Yes, I can reproduce.

Made a new test profile, only content:
```
Set-PSReadLineOption -HistorySaveStyle SaveNothing
```

This will indeed turn off history in PSRL *entirely*, it does not only not save any input history (expected), but I also cannot scroll back through command history, and command prediction etc. does not work any more.

Not sure if this is really intentional.
Using your already saved history (without adding any new history) is a very legitimate use-case.

**Comment by God-damnit-all** [comment]
> > So, I've noticed that if Set-PSReadlineOption -HistorySaveStyle SaveNothing is part of the initial set of startup commands, no history will be loaded.
> 
> You mean if you use that in your $PROFILE?

Yes, but also if you launch with `-NoE -f` or `-NoE -c` and `Set-PSReadLineOption -HistorySaveStyle SaveNothing` is included somewhere in there.

**Comment by God-damnit-all** [comment]
@Hrxn I've come up with a workaround:

```powershell
$_ = [Microsoft.VisualBasic.Interaction]::CreateObject('WScript.Shell')
$_.SendKeys('~')
$_ = [void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($_)
[void](PSConsoleHostReadLine)
[Console]::SetCursorPosition($Host.UI.RawUI.CursorPosition.X, $Host.UI.RawUI.CursorPosition.Y - 1)
```

**Comment by brian6932** [comment]
I've settled on this:
```pwsh
$PSReadlineOptions = Get-PSReadLineOption
$HistorySaveStyle = $PSReadlineOptions.HistorySaveStyle
$HistorySavePath = $PSReadlineOptions.HistorySavePath
[Microsoft.PowerShell.PSConsoleReadLine]::ClearHistory()
Set-PSReadLineOption -HistorySaveStyle SaveNothing
Get-Content $HistorySavePath -Last $MaximumHistoryCount | ForEach-Object {
    [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($_)
}
Set-PSReadLineOption -HistorySaveStyle $HistorySaveStyle
```
_Hopefully this is useful to someone._
