### ISSUE TITLE
[Idea] Path expansion

### ISSUE THREAD

**Issue by bazzilic** [PowerShell/PSReadLine#495]
It could be very useful if PSReadline could expand half-written file and dir names in paths. E.g., for a path `C:\My Projects\Current\files` you would do this

`> cd c\my\cur\fil`
hit [TAB] and...
`> cd C:\My Projects\Current\files`

That's something that I've been looking for in powershell for quite some time with no luck. I think I've seen this behavior in zsh with OhMyZsh, not sure though. This behavior is easy to see in command palettes in Atom or SublimeText.

As I understand, right now path completion is handled by powershell itself, PSReadline is just a proxy, so this might be a big task.

**Comment by gwojan** [comment]
You can do something like:

c:\my*\cur*\fil*<TAB> and autocompletion will work. It's not ideal but it does work.

There are modules out there that track your CD history and let you navigate partial paths.  I believe some of them are available on PowerShellGallery.

**Comment by gwojan** [comment]
The above comment looks like it ate my attempt at typing  TAB  after the partial path...

**Comment by lzybkr** [comment]
I'm going to close this because it doesn't really belong in PSReadline - if we did something, it should go in [PowerShell](https://github.com/PowerShell/PowerShell) itself, or something like [TabExpansionPlusPlus](https://github.com/lzybkr/TabExpansionPlusPlus)..

I will point out my sample key bindings to speed up navigation, see https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/SamplePSReadlineProfile.ps1#L434.
