### ISSUE TITLE
Right-click paste with \n comes out upside down?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSReadLine#496]
When using PSReadLine 1.2, and pasting text that has newlines _without_ carriage returns, the lines come out in reverse order.
![2017-01-20_22-32-31](https://cloud.githubusercontent.com/assets/192942/22171728/8a87382c-df62-11e6-9e8d-69e44c1e7d1d.gif)

**Comment by Tadas** [comment]
Seems to be happening because of this key handler: https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/KeyBindings.cs#L135
LF is interpreted as Ctrl+Enter and triggers `InsertLineAbove` which pushes each text line down as the right click paste is getting processed one char at a time. CRLF works fine because CR triggers `AcceptLine`. Ctrl+V paste works because it inserts all of the clipboard in one go.

### Workaround
`Remove-PSReadlineKeyHandler Ctrl+Enter`

**Comment by lzybkr** [comment]
Closing in favor of #579 which covers all of the known issues with right-click paste.

**Comment by pcunite** [comment]
Windows 10, 1909, just got bit by this bug.

**Comment by IanKemp** [comment]
How and why is this not fixed **more than 3 years after being reported**?
