### ISSUE TITLE
Many custom keybindings broken with latest build (1.0.200) from AppVeyor

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#580]
I just dropped the AppVeyor build 1.0.200 onto my machine and noticed a whole bunch of my custom key bindings no longer work.

```
Set-PSReadlineKeyHandler -Chord 'Ctrl+['                    -Function ViCommandMode
Set-PSReadlineKeyHandler -ViMode Command -Chord 'Ctrl+Shift+[' -Function DeleteLine
Set-PSReadlineKeyHandler -Chord 'Ctrl+Shift+['              -Function DeleteLine
Set-PSReadlineKeyHandler -Chord 'Alt+n'                     -Function HistorySearchBackward
Set-PSReadlineKeyHandler -ViMode Command -Chord 'Alt+n'     -Function HistorySearchBackward
```
This is just a few that I've noticed so far -- the most obvious ones that I use all the time. 😉 

I'll update as I find more.

Environment data
----------------

PS version: 5.1.15063.674
PSReadline version: 2.0
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)-->

Steps to reproduce or exception report
--------------------------------------

**Comment by lzybkr** [comment]
I made a change to basically ignore `Shift` most of the time so that key bindings aren't tied to specific keyboard layouts, and also so that the code is more portable because `Shift` is not always reported on Linux.

Assuming an English keyboard, `Ctrl+{` should work instead of `Ctrl+Shift+[`.

As for `Alt+n` - it works for me.

And thanks so much for testing pre-prerelease. I'm still waiting for the PSGallery team to accept prerelease modules, but it's great to get the feedback even earlier.

**Comment by gwojan** [comment]
@lzybkr Interesting... The ```Alt+n``` issue was due to the ordering of the commands. I had:

```
Set-PSReadlineKeyHandler -Chord 'Alt+n'                     -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Chord 'Alt+Shift+n'                     -Function HistorySearchForward
```

The ```shifted``` command was undoing the first command. Changing to ```Alt+N``` has resolved that issue.

However, I can not get ```Ctrl+[``` and ```Ctrl+{``` to work.

You're most welcome regarding the testing. I can't live without Vi mode! 😄 You and @srdubya have done an amazing job!

**Comment by lzybkr** [comment]
Thanks - I've confirmed `Ctrl+[` and `Ctrl+{` are not working.
