### ISSUE TITLE
Delay after Click cross button on Powershell window

### ISSUE THREAD

**Issue by MVKozlov** [PowerShell/PSReadLine#609]
Environment data
----------------
PS version: 5.1.14409.1012
PSReadline version: 2.0.0
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)

Steps to reproduce or exception report
--------------------------------------
1. start `Powershell -noprofile`
2. PSReadLine autoloaded
3. Close PS window by mouse pressing cross button
4. PS Window closes after 5-7 seconds

- when `exit` typed, PS closes fast
- when old version (v1.2) of PSReaLine used, PS closes fast

**Comment by lzybkr** [comment]
Thanks for the detailed bug report - it was a bit of a pain to track down because:

* it didn't reproduce on Win10
* this was an old problem and there were recent code changes near the original fix - leading me in the wrong direction for a bit
* you can't debug this problem, the OS kills the process before you really get a chance to debug
* I didn't believe `git bisect` - because it was such a small commit that seemed harmless

At any rate, I believe it's fixed now.
