### ISSUE TITLE
2.0.0 prerelease builds do not seem to receive Control-C (on Linux)

### ISSUE THREAD

**Issue by DHowett** [PowerShell/PSReadLine#610]
Environment data
----------------

```powershell
PS version: 6.0.0-beta.9
PSReadline version: 2.0.0
os: Linux crux 4.14.0-1-amd64 #1 SMP Debian 4.14.2-1 (2017-11-30) x86_64 GNU/Linux
```

Steps to reproduce or exception report
--------------------------------------

Press ^C.

### 1.2
```
$ pwsh -NoProfile
PS> (Get-Module PSReadLine).Version                                              

Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      -1     -1      

PS> Set-PSReadlineKeyHandler -Key "Ctrl+C" -ScriptBlock { write-host "Ctrl-C captured" }                                                        
PS> [here, press ^C]
Ctrl-C captured
```

### 2.0
```
$ pwsh -NoProfile
PS> (Get-Module PSReadLine).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      0      -1      


PS> Set-PSReadlineKeyHandler -Key "Ctrl+C" -ScriptBlock { write-host "Ctrl-C captured" }
PS> [press ^C some more, but nothing happens]
```

**Comment by lzybkr** [comment]
Try `Ctrl+c` instead, that should work correctly with V1.2 and V2.0.

I wanted to move away from requiring `Ctrl+Shift+c` when you really wanted uppercase because in some cases, the shift state is layout dependent (normally non-letters).  The goal is that the character is all you need, shift is inferred for you.

This is mostly working as intended, but it's somewhat useless on non-Windows because the shift state isn't reported for Ctrl+<any letter>.

Hopefully this isn't too annoying of a change to make, if it turns out to be a big deal, then maybe I'll have to revisit the change.

**Comment by DHowett** [comment]
@lzybkr thanks for the info. In all that, I neglected to mention that its default binding doesn't work either (`CopyOrCancelLine`). :smile:

**Comment by DHowett** [comment]
Ugh, I mean: Its default binding doesn't work even if I do not manipulate it with Set-PSReadlineKeyHandler and/or load without my profile.

**Comment by DHowett** [comment]
Dug in a little bit:
Should PSReadLine be still be setting `Console.TreatControlCAsInput`? It looks like it was stripped out during the PlatformWindows split. I'm trying to test that out, but there seem to be significant hurdles to .NET development on Linux.

**Comment by lzybkr** [comment]
Nice catch - that's probably it.

The binary built works everywhere, so you can build on Windows and copy it to Linux if you want to try that fix.

**Comment by lzybkr** [comment]
I just verified the fix, you can grab a build out of AppVeyor to verify.
