### ISSUE TITLE
Supporting Vi movements in multiline buffer

### ISSUE THREAD

**Issue by springcomp** [PowerShell/PSReadLine#789]
I would like to use `PSReadLine` in Vi editing mode while working with multiline buffers, as I find myself doing a lot in PowerShell. Is there a builtin way to do this?

Not finding anything obvious, I started implementing it, with the <kbd>G</kbd> and <kbd>gg</kbd> commands.
You can see the [provisional commit](https://github.com/springcomp/PSReadLine/commit/cfc315ca76c84503fab3ee947ee15a116dfd83fe) here.

Would such a development be of interest ?
In that case, would you accept a pull request to that effect ?

To further complement my development, I'm trying to write the corresponding tests. However, I have a hard time using the `Test` method to accept a sequence of keys simulating a multiline buffer. I have tried both `_.Enter` and `_.CtrlEnter` but none of them produce my expected result.
@

**Comment by gwojan** [comment]
@springcomp, multi-line editing in Vi mode sort of works right now but the experience could use improvement. What I do is make sure my `$env:EDITOR` and `$env:VISUAL` variables are set to `vim` or `nvim` and just edit whatever command line I'm working on directly in the full editor. `<esc>v` is your friend... 😉 

Vim works pretty well in a Windows 10 console session now but I had switched to Neovim because of weird display issues in the original Windows 10 Creator's update. If you use Neovim make sure you set `$env:TERM = 'xterm-256color'`. All in all, I'm pretty happy with the experience in latest PowerShell console sessions using `PSReadLine + Neovim/Vim`.

**Comment by lzybkr** [comment]
As @gwojan mentions - basic multi-line editing works. I'm happy to accept improvements like you've implemented.

I'm happy you've written a test - I do require tests for most PRs.

Multi-line is tested, see [an example](https://github.com/lzybkr/PSReadLine/blob/14ddf0c0325776482bd28c1e99b83346478d5070/test/RenderTest.cs#L113). Rarely there can be unexpected interactions between tests which can be annoying to track down, so you can try running just your test first.  If that still fails, well, testing can be a little finicky sometimes.

If it passes when run by itself, there is probably a side effect from some other test causing problems. Use binary search to run sets of tests to help determine which test is causing problems, that usually quickly leads to a solution with a little intuition or some debugging.

**Comment by springcomp** [comment]
Thank you very much. That got me on the right track.
