### ISSUE TITLE
How to use DECXCPR? (Report Cursor Position)

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PSReadLine#799]
The conhost Virtual Terminal Sequences [doc](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) describes some "query" codes, among which is DECXCPR, which allows you to query the cursor position:

| Sequence | Code | Description | Behavior |
|----------|------|-------------|----------|
| ESC [ 6 n | DECXCPR | Report Cursor Position | Emit the cursor position as: ESC [ <r> ; <c> R Where <r> = cursor row and <c> = cursor column |

> **Note** These queries will emit their responses into the console input stream immediately after being recognized on the output stream while ENABLE_VIRTUAL_TERMINAL_PROCESSING is set. The ENABLE_VIRTUAL_TERMINAL_INPUT flag does not apply to query commands as it is assumed that an application making the query will always want to receive the reply.

I'm trying to figure out how to use this sequence. Ideally what I'd like to be able to do is register a handler of some sort, so that when I emit `CSI 6 n` to the output stream, my handler gets called with the info from the "reply" VT sequence that conhost injects into the input.

I came to look around the source, and found that it looks like @parkovski has already added the foundation for handling VT sequences in the input stream (#564). Fantastic! But now I need to figure out how to wire it up.

I'm hoping that @parkovski or lzybkr could give some direction / guidance / jumpstart on what the right way to do that would be, which would save me a lot of time trying to understand how things work based solely on the code.

TIA!

**Comment by lzybkr** [comment]
Is there some reason you can't just use `Console.CursorTop` and `Console.Left`?

**Comment by SeeminglyScience** [comment]
I use it occasionally because it gives the position relative to the view port instead of the whole buffer, similar to how `Console.CursorTop` already works on non-Windows platforms.

@jazzdelightsme PSRL will only be reading stdin when it's trying to read a key.  That means if there is a key handler running, or a command entered at the prompt is running, PSRL won't be looking for the sequence.  If that still sounds like what you want, could you explain in a little further detail what you are trying to accomplish?

Side note, the more direct answer to "how you to use DECXCPR" is something like this:

```powershell
$isOnColumn = $false
$line = [System.Collections.Generic.List[char]]::new()
$column = [System.Collections.Generic.List[char]]::new()

[Console]::Write("$([char]27)[6n")
while ($true) {
    $key = [Console]::ReadKey($true)
    if ($key.KeyChar -in [char]27, [char]'[') {
        continue
    }

    if ($isOnColumn) {
        if ($key.KeyChar -eq 'R') {
            break
        }

        $column.Add($key.KeyChar)
        continue
    }

    if ($key.KeyChar -eq ';') {
        $isOnColumn = $true
        continue
    }

    $line.Add($key.KeyChar)
}

$line = [int]::Parse([string]::new($line.ToArray()))
$column = [int]::Parse([string]::new($column.ToArray()))
return "$line, $column"
# 40, 1
```

**Comment by jazzdelightsme** [comment]
Thanks guys!

`[Console]::CursorTop` doesn't seem to work in my situation--a tty hooked up to an Ubuntu18.04 Docker container--because it always reports "52".

What I was hoping to be able to accomplish is to be able to write some output like:

```powershell
Write-Host "(${DECXCPR}checking) blah blah"
```

And then somehow harvest the position reported, and then later use that position to come back and overwrite "checking" with "ok" or "FAILED" or something.

But actually, I don't know if it's `[Console]`'s fault... I tried bash in my container, and it reports... nothing for the row:

```
root@87ad6653c162:~# echo -e "hi \e[6n there \e[6n"
hi  there
root@87ad6653c162:~# ;4R;11R
```

So perhaps my idea of using DECXCPR is doomed, anyway. *sigh*

**Comment by SeeminglyScience** [comment]
@jazzdelightsme Yeah you have to read the response from stdin like the example I gave, it doesn't get replaced in the output stream or anything like that.

Also the implementation of `Console.CursorTop`/`Left` on Unix-like platforms already utilizes that escape sequence.  The reason it is reporting the same thing every time is because it is relative to the visible space on the screen, not the total buffer.  I'm not aware of a way to obtain the latter on Linux/Mac unfortunately.

**Comment by jazzdelightsme** [comment]
Okay, thanks guys.

**Comment by determin1st** [comment]
it's not `DECXCPR`, its just `CPR`, extended `CPR` returns page number which no terminal emulator author utilized in the sensible way. the sequence of `DECXCPR` is `<ESC>[?6n`

the sane application of `DECXCPR` these days would be returning the maximal page number according to vertical scrollback value, 's like what windows api returns about buffer capacity

i came here from google search, because again, looks like nobody utilized DECXCPR in the useful way..
