### ISSUE TITLE
Position of cursor when using HistorySearchBackward

### ISSUE THREAD

**Issue by MarcLaf** [PowerShell/PSReadLine#944]
Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta4
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
I've noticed that when using PSReadLine 2.0 and above, when using up to go backwards through history, the following customization dumps the cursor to the beginning of the line, not the end as in 1.2 (or without customization).

```
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
```

Every time Windows 10 updates to a new version, 2.0 gets installed and I either need to remove 2.0 or comment out those lines in profile. Is this behaviour expected and is what others are seeing when using it or is there something else on my system that's causing it?

**Comment by lzybkr** [comment]
Try:

```PowerShell
Set-PSReadLineOption -HistorySearchCursorMovesToEnd
```

**Comment by MarcLaf** [comment]
Thank you I had no idea it was even an option. So I'm guessing cursor going to beginning is expected behaviour then. Appreciate the fix.

**Comment by lzybkr** [comment]
The behavior matches bash. The default is for the cursor to stay in place, so if you typed something, e.g. `cd `, then typed <kbd>UpArrow</kbd>, the cursor would remain after `cd `, not at the beginning of the line.

I suppose if the command line is empty it's a bit silly to require this option.

**Comment by MarcLaf** [comment]
Ah okay I understand now. I never thought about how that would affect the history searching based on partial commands entered. Usually I'm wanting to run a command again but change the last few characters so having it stay at the beginning was requiring extra steps (End).

**Comment by Gregory-K** [comment]
I'd like to mention that the PSReadLine behaviour does not match Bash's.
Bash is more intelligent than that:  
- It always puts the cursor to the end of the previous command+arguments, and if you edit that line, only then, it retrieves identical history entries (up to the cursor position).
- On an empty command line it just rolls history backwards (cursor at the end of previous lines). You have to write something or place the cursor to the desired position of a recalled line in order to filter backward/forward history recalls.

No matter what, the cursor is always where it is supposed to be for the least possible amount of movements towards your next editing step.  
It would be nice for PSReadLine to match Bash on this. Otherwise, `HistorySearchBackward/Forward` breaks established & expected UX.
