### ISSUE TITLE
Discussion: Syntax Highlighting switch to TM grammars

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSReadLine#981]
This would be a PSRL 3.0 type item, but I notice that PSReadline basically follows its own rules when it comes to syntax highlighting, and this leads to a lot of inconsistencies with theming, especially when used as, say, the integrated terminal in VSCode.

Would it make sense to adjust PSRL to use the textmate grammar shared by PSES and most other powershell editors for highlighting? https://github.com/PowerShell/EditorSyntax/blob/master/PowerShellSyntax.tmLanguage. It wouldn't have to implement a whole textmate library, just parse the tmLanguage file and use the regexes to define member, type, etc. and then have those items as PSReadLineOption exposed for color.

Then the PSReadline experience would be consistent with all editors using PSES or the tmlanguage highlighting.

**Comment by lzybkr** [comment]
Unlike many other editors, PSReadLine accurately colors token because it gets the tokens from the PowerShell parser.

Most (maybe all) inconsistencies you see are simply bugs in the other grammars. Such bugs might not be easy to fix though. Regular expressions tend to work reasonably well, but can't really be as complete or correct as a proper parser.

**Comment by JustinGrote** [comment]
@izybkr I just came back here to say that of course the AST parser is the best way to go in this regard, but maybe align the token color names with the PSES tmlanguage for consistency.

Anyone, I'll close this for now and open separate spot-cases for areas where I can't make it consistent.

**Comment by lzybkr** [comment]
Oh, that is mostly reasonable, as long as they can be aliases of existing token kinds.
